### ISSUE TITLE
non-linear parse times

### ISSUE THREAD

**Issue by james-q-arnold** [antlr/antlr4#1035]
We have a grammar with a rule similar to the following:

```
pattern: primary+ ( OPERATOR primary+ )*
```

When parsing a long sequence, this gives non-linear parse times:

- 100 items:  00:04 (mm:ss)
- 500 items:  00:57
- 1000 items:  04:09
- 1200 items:  05:50

Is this performance reasonable (and expected)?
Any suggestions for revising the rule to avoid this behavior?
Our input frequently includes long sequences, and we need
to solve this issue.

**Comment by ericvergnaud** [comment]
Hi,
have you tried:
pattern:
    primary
    | pattern primary
    | pattern operator primary
   ;
Eric

**Comment by ericvergnaud** [comment]
Btw, GitHub is not the place for support, you should really be asking this question on the google group.

**Comment by james-q-arnold** [comment]
Well, if my tools behaved like this, I would consider it a defect.
Thus I filed the report on github.  But I do appreciate the help
and suggestion for rewriting the rule.  I'll try it.

Best regards,

Jim Arnold

**Comment by sharwell** [comment]
The original rule is actually written in a form which could be LL(1). This means the performance problems are due to some other aspect (specifically, interaction with other rules defined in your grammar but not down here). Simply rewriting the rule as left-recursive probably wouldn't make a difference.

**Comment by james-q-arnold** [comment]
You are correct.  I tried rewriting the rule---no significant difference.

Do you have a suggestion, other than keep replacing other rules until
I find something that changes the behavior?  Ideas for what type of rules
might cause this effect?

**Comment by sharwell** [comment]
This is typically caused by long lookahead and/or ambiguities in the grammar. I know the IntelliJ tooling includes some features to identify decisions and inputs that trigger the lookahead. Aside from rewriting rules, the use of two-stage parsing is known to improve performance in a wide variety of scenarios. If that does not work for you, my fork of the project supports DFA caching for decisions which require LL mechanics (the Boo parser required this feature to reach acceptable performance without rewriting their very large grammar).

**Comment by sharwell** [comment]
Note that full context DFA is extremely memory intensive and is known to make some real-world grammars much slower, which is why it's disabled by default.

**Comment by james-q-arnold** [comment]
OK.  I'll review the existing rules.  But use of name+ and (expression)*
are likely not the issues?  I would like to preserve those, rather than
rewriting everything to rule-based iteration/recursion.  Seem ok?

Thanks for your help.

**Comment by james-q-arnold** [comment]
With Sam's suggestion, I found an ambiguity in the grammar.
The rule given above appeared to be relevant to the problem
but actually was not.  Closing this issue.
