### ISSUE TITLE
Allow a rule-delimited lexer and/or parser sequence 

### ISSUE THREAD

**Issue by SimonSntPeter** [antlr/antlr4#1071]
This type of construct is common:

params: '(' expression ( ',' expression )* ')' ;

perhaps allow a shorthand for it, something like:

params: '(' expression *{ ',' } ')'

where some separating rule (comma literal here but could be any lex/parse rule) can be given. 
Also applies to + as well as * repetition.  Braces { and } are just for example.
I don't know if this really has much value though.

**Comment by sharwell** [comment]
This is a common pattern in grammars. It would be interesting to see it simplified, but I'm not sure what the syntax would look like.

**Comment by KvanTTT** [comment]
Maybe something like this: ```params: '(' expression (',' ...*) ')'```?
This syntax is used in [Transact-SQL description on msdn](https://msdn.microsoft.com/en-us/library/ms177563(v=sql.120).aspx).

**Comment by SimonSntPeter** [comment]
@KvanTTT - that would be a good syntactic option, but I'm thinking about it a bit more widely. Some questions then,
* I agree with Sam Harwell that it's a very common pattern in grammars, in which case absence of support for it antlr (and bison IIRC) strongly suggest it's not that important for other reasons.
* Adding a feature is dead easy, but removing it is almost impossible, then you have to support it forever. Something MS and intel keep learning.
* If this were to be considered as an addition, is it actually just one facet of a more general feature that would be of greater value? Only thing I can think of for this is minimum length of repetitions (couple of places in my grammar I would like to specify 2 or more, or 3 or more arguments) so have a regexy min/max repetition specifier { }. I'm never suggesting this, just looking for broader patterns!

So far I can't justify this to myself.

**Comment by SimonSntPeter** [comment]
Weirdo confusing UI, sorry.

**Comment by sebadur** [comment]
A very broad possibility of implementation for your case should already be accessible via predictions:
```params: '(' ( ({$xp!=null}? ',')? xp=expression )+ ')';```
Or replace the ```+``` with ```*``` for more common use. You even could do strange things like this:
```params: '(' ( ({$xp!=null}? between ',')? xp=expression )+ ')';```

**Comment by jimidle** [comment]
Specifying a range of production occurrences in the lexer or parser isn't a
good idea in my opinion. You get much better error messages from a semantic
check after gathering as many repetitions as there are (including 0):

Line 567, offset 24: The function 'deepthought()' requires 42 arguments,
not 54.

With a generated check you would get something like:

production 'expression' must occur 42 times.

Which does not help the users, who know nothing of your grammar productions.

These things sound good but are only slightly useful for the grammar author
and tend to remove information for the end user. It is virtually always
better to push errors as far down the tool chain as you can, so that you
have contextual information to enhance the error messages.

However, open ended repetitions such as function arguments might gain
something from a bit of syntactic sugar I suppose. It could also just be
bikeshedding ;). So something like this:

funcargs: elist+=expression{'(', ',', ')'} ;

Does that really help though? Now you have to know what this is doing. The
fully written productions might be:

parenargs: '(' args? ')' ;
args: elist+=expression (',' elist += expression)*;

Which is probably easier to read. You check the arg count semantically, not
at parse time.

In general, while this is a common thing to specify in a language, even
strange languages like SQL only need two or three such productions. My
feeling therefore is that there isn't much to be gained from this.

It might be more useful to create a shortcut in the editor plugins:

parenargs: expression

Select expression, press a magic key sequence and it expands it. Even that
seems a bit overkill to me though.

Jim

**Comment by SimonSntPeter** [comment]
> In general, while this is a common thing to specify in a language, even strange languages like SQL only need two or three such productions 

Nope, it's all over the place in SQL. But enough to justify a new repetition construct?

> ...bikeshedding

Agreed. Closing this.
