### ISSUE TITLE
Ideas for improvement

### ISSUE THREAD

**Issue by Kaba2** [antlr/antlr4#1114]
Here are some ideas for improvement in ANTLR4, to be toggled with a switch.

1. **Provide ?, +, and * their own parse-tree nodes.** For example, 'n'+ 'a' would always provide a parse tree of _two_ nodes. With input 'a', the repetition node would be empty. This way the structure of the rule-node is invariant to repetition. Current workaround: separate each use of ?, + and * into its own rule.

2. **To form a context-name, combine the label of an alternative with the name of the parent rule.** For example, if the parent rule is 'expression', and it has labels 'add' and 'multiply', then produce the contexts named 'addExpression' and 'multiplyExpression'. Current workaround: write the 'Expression' suffix to each label yourself.

**Comment by SimonSntPeter** [comment]
I'm adding this here as I don't want to open a new issue for something so small, and I suppose it's an improvement request though a very minor one. 
Unconditionally recursive rules seem not to be picked up by antlr, eg.
`aa : 'silly' aa ;`
presumably produce an unbranching cyclic graph in antlr, would it be possible to easily find these?
This is the first time in months of use I've bumped into this and it really is obvious when it happens so it's very low on any list.

**Comment by parrt** [comment]
4.5.3 will allow option `contextSuperClass=org.antlr.v4.runtime.RuleContextWithAltNum` (in Java target that class exists) so you will always get alt num to solve (2) :)  Fixed by 9e98714a1d955e2a8f588e304551c074651ce030.

I like idea but can't see adding an option for (1) but thanks!

For (3), it seems to work for me; not a good rule but it gens a rule function.
