### ISSUE TITLE
Bad parsing of ternary expressions

### ISSUE THREAD

**Issue by ComradeP** [antlr/antlr4#1119]
Here's a reduced grammar fragment:

```
grammar between;

expr : Id
     | expr 'and' expr
     | expr 'between' expr 'and' expr
     ;

Id  : [a-zA-Z]+;

WS  :  [ \t\r\n\u000C]+ -> channel(1) ;
```

Here's what happens:

```
$ echo var between min and max and otherCondition | \
    java -cp .:$HOME/semmle/code/resources/lib/antlr-4.5.1-complete.jar \
             org.antlr.v4.gui.TestRig between expr -tree
(expr (expr var) between (expr (expr min) and (expr max)) and (expr otherCondition))
```

That is, instead of having a top-level `and` node which contains `var between min and max` and `otherCondition` as children, we have a top-level `between` node whose bounds are `min and max` and `otherCondition`. I believe this is the wrong parse tree, since the production for the `and` rule is above the production for the `between` rule, and so should have matched first.

Reordering the productions, or making one or both right-associative, does not seem to make any difference. It seems to me that there's something subtle going on here with the conversion of ternary productions to binary. Here's what the `-Xlog` file contains regarding the left-recursion elimination:

```
2016-02-19 16:47:59:433 left-recursion LogManager.java:49 expr
    :   ( {} Id<tokenIndex=9> 
        )
        (
          {precpred(_ctx, 2)}?<p=2> 'and'<tokenIndex=15> expr<tokenIndex=17,p=3>
                  | {precpred(_ctx, 1)}?<p=1> 'between'<tokenIndex=23> expr<tokenIndex=25> 'and'<tokenIndex=27> expr<tokenIndex=29,p=2>
        )*
    ;
```

Unfortunately I'm not completely sure how to read this.

Is this behaving as intended? Am I missing something in terms of how the grammar should be written to give the parse I want?

**Comment by KvanTTT** [comment]
Maybe it's better and clear to use the following rule?
```ANTLR
expr : Id
     | expr 'and' expr
     | expr 'between' expr
     ;
```

**Comment by ComradeP** [comment]
Sure, but that doesn't quite represent the right parse tree. You could imagine that I was modelling something like the `?:` ternary operator, where `expr : expr` would not be a valid expression.

Or is that the problem, really? The second and third arguments of the ternary expression could on their own indeed form a legal expression; that's just part of the language I'm trying to parse. Nevertheless, I would like to prefer a top-level `and` node to the ternary production rule, which I thought should be achieved by production precedence.

**Comment by sharwell** [comment]
There is no such thing as a ternary expression in ANTLR. Your example `expr` rule has two binary operators:

1. One has the operator `'and'`
2. One has the operator `'between' expr 'and'`

In the second case, the `expr` which appears as part of the operator breaks out of the precedence hierarchy completely, and will match the longest subexpression it can.

The impact of this limitation is rather simple to word it turns out - you can't have a binary operator which is also the same operator used for a ternary expression.

**Comment by ComradeP** [comment]
Hm, that's a helpful explanation, thanks.

It's a bit awkward, though. Consider, for example, a more complex expression like this: `x between minX and maxX and y between minY and maxY`. In the language I'm trying to parse, this has to become `(x between minX and maxX) and (y between minY and maxY)`, which, I thought, could be achieved neatly by giving the `and` rule higher precedence than the `between` rule. As you say, the desugaring into two binary-expr rules rather breaks that.

Am I right in thinking of this as an inherent limitation rather than a bug? Can you help me think of a way of phrasing the grammar in a way that does the right thing on the compound example above?

**Comment by SimonSntPeter** [comment]
@ComradeP: My code gives this tree for this input 
`select sometheing where x between minX and maxX and y between minY and maxY` 
which I think is what you want (search_condition is the relevant subtree, indicated)

![capture](https://cloud.githubusercontent.com/assets/16326873/13203967/7bf66ade-d8bb-11e5-9871-4b84f9227f24.PNG)

I did it the old-fashioned way:

```
search_condition :
        disjuncted_search_condition
    ;

disjuncted_search_condition :
        conjuncted_search_condition
        (
            or
            conjuncted_search_condition
        ) *
    ;

conjuncted_search_condition :
        opt_negated_predicate
        (
            and
            opt_negated_predicate
        ) *
    ;

// optionally negated quantifier, between, in, like or comparison
// (ie. relational) expression, or other 
opt_negated_predicate :
        ( not ? ) predicate
    ;

predicate :
        binary_relop
    |
        all_any_binary_relop // quantifier
    |
        between_check
    |
        in_check
     ...


between_check :
        expression betweenness expression and expression
    ;

betweenness : between | not_between ;
```

Now, the answer from @sharwell is interesting because I was going to try to 'sugar' up and 'antr-ify' the code to remove `disjuncted_search_condition` and `conjuncted_search_condition` and his answer says this can't be done. That's saved me some time, great.

HTH

jan

**Comment by ComradeP** [comment]
@SimonSntPeter -- thanks, that's helpful; indeed I was also thinking along similar lines, given the somewhat odd behaviour of ANTLR's left-recursion-elimination here.

There's a subtlety, though, namely that I would like to consider `x between y and z` as a legal expression -- it's something that has `boolean` type, rather than merely being a particular restriction on a search condition. In the full grammar, that means that you could initialise a variable with something like `x = y between min and max;`. If I try to unwind the precedence order manually as you suggest, ANTLR complains about mutual-left-recursion ("between.g4::: The following sets of rules are mutually left-recursive [expr2, conjunct]"), which I do believe is a limitation. In terms of your grammar, the `between_check` rule starts with an `expression` nonterminal, which means that the `expression` nonterminal itself cannot ultimately be a `between_check`.

Basically, I was hoping that ANTLR's rule precedence would help me get away with a simple and understandable grammar here. :-)

@sharwell -- I was intrigued by part of your response, namely "In the second case, the `expr` which appears as part of the operator breaks out of the precedence hierarchy completely, and will match the longest subexpression it can." Is there a technical reason why the desugaring of ternary expressions cannot respect the rule precedence order? Is this limitation described somewhere? I was struggling to find a clear explanation of how exactly ternary expressions are handled [other than "they are just binary expressions in disguise" in the FAQ](https://github.com/antlr/antlr4/blob/master/doc/left-recursion.md), and so was planning to dig into the source next, but if there's a summary somewhere that'd be very helpful.

**Comment by SimonSntPeter** [comment]
@ComradeP -- Antlr's left recursion removal is straightforward; it can remove immediate left recursion only. Also per @sharwell's answer, a longer pattern is preferred over a shorter one, so `expr 'between' expr 'and' expr` is picked over `expr 'and' expr` because the former is quite simply longer, and that makes perfect sense, and seems desirable behaviour to me.
Antlr can't do magic with left recursion removal, I suspect it's extremely hard, maybe impossible in general, so the burden lands back on the programmer. That's ok, time to go old-skool.
Regarding your code, I based my grammar on a published BNF spec which had `search_expression` given differently from `expression`. I agree, I wouldn't do that but I am where I am... I butchered my grammar to get something working. The solution is to hang additional stuff off the right-hand side of `expression`. Code is

```
expression :
		disjuncted_search_condition
	|                           // this new alt [1] below is the relevant bit
		disjuncted_search_condition        
			( betweenness expression and expression) [1]
    ;

disjuncted_search_condition :
        conjuncted_search_condition
        (
            or
            conjuncted_search_condition
        ) *
    ;

conjuncted_search_condition :
        opt_negated_predicate
        (
            and
            opt_negated_predicate
        ) *
    ;

opt_negated_predicate :
        ( not ? ) predicate
    ;

predicate :
		integer_const
    ;
```

[1] is hoisted out of my old code (see prev pos) and tacked on at the end, at the level of expression. Sorry it's not the clearest but hopefully you get the idea.
For this input
`declare @i int = 3  between 9  and 10 and 4 between 65 and 76`
You get this tree
![capture](https://cloud.githubusercontent.com/assets/16326873/13219536/839c7f50-d968-11e5-8837-cf6fa6e973ad.PNG)

Separately I'd also like to understand Sam's comment that ternaries are "just binary expressions in disguise" - Sam, can you elucidate?

**Comment by ComradeP** [comment]
@SimonSntPeter, am I misreading your screenshot or is that actually the wrong parse tree? The node you highlighted seems to be: `(3 between (9 and 10) and (4 between 65 and 76))`, whereas I would hope for `(3 between 9 and 10) and (4 between 65 and 76)`...

**Comment by ComradeP** [comment]
Oh, just saw your edit, sorry about that. :-)

**Comment by SimonSntPeter** [comment]
@ComradeP Ok, took a while, I'm out of practice with this stuff. I hope this is right.
Input is
`declare @i int = 3 between 9 and 10 and 11 and 4 and 6 between 65 and 76 and 999`
Note I've put in some extra 'and's of items which aren't betweens, to check it behaves right. 
Code is 
```
expression :
        disjuncted_search_condition
	;

disjuncted_search_condition :
		conjuncted_search_condition
        (
            or
			conjuncted_search_condition
        ) *
    ;

conjuncted_search_condition :
		poss_between_decl
        (
            and
            poss_between_decl
        ) * 
    ;

poss_between_decl :
		item ( betweenness item and item ) ?
	;

item :
		integer_const
    ;
```
Tree is 
![capture](https://cloud.githubusercontent.com/assets/16326873/13226173/0c974f3c-d988-11e5-8ae9-578697aee2c7.PNG)

@sharwell Given your comment that we basically can't have binary and ternary operators which share an operator, I guess that means due to this one special case, everything would have to be rewritten from nice immediate left recursion into right productions - would I be right? I'll probably have to do the same eventually as well if that's the case.

**Comment by ComradeP** [comment]
@SimonSntPeter -- thanks for all the effort you're putting into this!

I note that your last suggestion actually only allows `item`s as the `between` bounds, which is a significant restriction from the original, which allowed arbitrary expressions. If you do that, then there is no ambiguity any more about how `x between 1 and 2 and 3` should bracket.

I'm starting to wonder whether my goal is achievable at all. Certainly it's a highly ambiguous specification, but it feels like assigning higher precedence to `and` than to `between` it ought to be possible to get the right parse. In particular, it seems easy to determine what the "right way" is by hand, which suggests there is an algorithm for it. I'm not sure if expressing that fits nicely with `antlr`'s view of left recursion, though, given its handling of ternary expressions and the fact that it ignores rule precedence for the middle recursive rule reference.

**Comment by SimonSntPeter** [comment]
@ComradeP No probs, it's useful to get practice with the old way and if I end up rewriting my own stuff, it'll be handy.
I omitted the general expression and used only `item` for brevity otherwise I'd have done 
`item : integer_const | other-stuff | more-other-stuff | '(' expression ')' ;` I was just trying to show the principle.

> If you do that, then there is no ambiguity any more about how `x between 1 and 2 and 3` should bracket
 
I'm not sure I understand. Depending on your preferred precedence, it could be `x between (1 and 2) and 3` or `x between 1 and (2 and 3)`. You need to know what precedence you want and it's not clear to me.

> but it feels like assigning higher precedence to and than to between it ought to be possible to get the right parse

If you gave 'and' a higher precedence then this input I used above
`declare @i int = 3 between 9 and 10 and 4 between 65 and 76`
would be parsed as
`declare @i int = (3 between 9 and 10) and (4 between 65 and 76)`
Which is what you want and what my 2nd example gives (I think) if you gave it lower it would get you something horrid like
`declare @i int = 3 between 9 and ((10 and 4) between 65 and 76)`

In my 2nd example, try replacing `item` with `expression` to get this 

```
poss_between_decl :
        expression ( betweenness expression and expression ) ?
    ;
```

and see what happens (I dunno and I can't experiment now). How you express your grammar in the way is showed (if done properly; as mentioned I'm out of practice) controls how your precedence is imposed. If you have a clear and consistent precedence in mind you can get it to work. Play around.

**Comment by SimonSntPeter** [comment]
@ComradeP last post wasn't very helpful. Put a subset of your grammar (say integers only, something minimal but enough to be useful) with clear precedence here and I'll try to get it working.

**Comment by SimonSntPeter** [comment]
@ComradeP Sorry, I meant *my* last post wasn't very helpful, not yours. Dump a grammar here and I'll try to implement it.

**Comment by ComradeP** [comment]
@SimonSntPeter -- thanks for your tenaciousness :-)

Basically, I think a slight extension of the original grammar captures all the aspects I'd like to see in action. Here's a naive version:

```
grammar between;

expr : Id
     | expr op expr
     | '(' expr ')'
     | expr 'between' expr 'and' expr
     ;

op : 'and' | 'or' | 'implies';

Id  : [a-zA-Z]+;

WS  :  [ \t\r\n\u000C]+ -> channel(1) ;
```

The key property I'm after is that the `between` rule should have the lowest precedence. This means that in the following examples, for each `between` node the second and third `expr` production should only contain an identifier tree:

 - `x between y and z and x between y and z`
 - `foo and x between y and z and foo`

Ideally, the following should also parse if you remove the parentheses: `truth between (a between b and c) and (x between y and z)` [1].

In my experiments, I also found that this can easily make antlr's backtracking blow up, so as a performance test I'm interested in how long it takes to parse `x between y and z and` (repeated 10 times) followed by `z`.

Note that in particular this requires us to get around @sharwell's "In the second case, the `expr` which appears as part of the operator breaks out of the precedence hierarchy completely, and will match the longest subexpression it can."

[1] I think technically speaking Boolean values are not legal as bounds in the `between` expression in the actual language I'm considering, but nevertheless it should be possible to pretend they are and get the expected parse, right?

**Comment by SimonSntPeter** [comment]
@ComradeP, rather than keep adding here, let's move it offline. If you have gmail you can contact me directly. Go to <https://groups.google.com/forum/#!topic/antlr-discussion/err1AgcOb-4> and I'm "rtm...@googlemail.com". I'm struggling with this precedence thingy BTW. Thought it would be easy, hah.

**Comment by SimonSntPeter** [comment]
@ComradeP, I'm playing around and getting my head around it. Turns out you can control precedence in the grammar by explicit writing of the parse rules, but that's not solving your problem.
I can get this to parse `truth between a between b and c and x between y and z` as you want because there are 3 `between`'s and 3 `and`'s so there's only one legal parse, however `a between b and c and x between y and z` is ambiguous; 2 `between` but 3 `and`'s.
If we try to fix that by making `between` the lowest precedence then I think you're stuffed because how do you join statements together with `and/or/implies`? You can't because to do so they have to be even lower precedence than `between`.
If you make `and` lowest precedence followed by `between` then `a between b and c and x between y and z` gets parsed left to right as `a between b and (c and x between y and z)` because the first `and` is assumed to belong to the `between` so the subsequent expression gets parsed as a big lump belonging to that `between`. Pretty much how `2 * 3 * 4 * 5` is parsed as `2 * (3 * (4 * 5))` not as a balanced tree `(2 * 3) * (4 * 5)`.
I think that may be the key, really. You'd never expect a parse to produce a balanced tree without further constraints (I could be wrong though).
I don't know if what you want is possible as such. It may be but right now I don't know how to do it. Sorry.
Some points: one alternative is to modify the grammar to require brackets round the construct, if that's a viable option for you eg.
`between_expr : '('  expr  'between'  expr  'and'  expr ')' ;`
This is unambigous which means no human will get confused (personally I seriously dislike over-reliance on precedence in expressions as I've seen horrific bugs when - not if - people get it wrong), and will also prevent the exponential blowup in parsing. That can matter. Some years ago I was talking to a guy maintaining an in-house own-language-to-sql translator and he reported that on a deeply nested expression using ternary c-style `...?...:...` it was taking *minutes* to finish successfully. Got to wonder if there wasn't other factors but still...
Other option is to constrain the between to only take `ID` or bracketed subexpressions. Awful suggestion I think.
Last and ugliest but perhaps best is to parse as-is then use code to rewrite the parse tree. Perhaps treat the `between` as an independent binary operator, the `and` likewise (shades of what Sam Harwell said about ternary operations being binaries in disguise?) then process after by finding `between`'s followed by and `and`'s and replacing them with a new subtree.
That's my best shot so far, I'm afraid.

**Comment by ComradeP** [comment]
@SimonSntPeter - hm, I think you're onto something with your point about bracketing. Balanced parse trees are not what you tend to end up with, and even though I don't think it's balance I want it's quite related -- it's minimality of what's captured by the `between` rule relative to other possible parses --, the underlying issues are similar. In particular, experimenting with left-right or right-left associativity doesn't immediately help.

Thus, while Sam's point about precedence not applying to the middle recursive call of a ternary rule is still confusing to me, perhaps ANTLR's style of grammar is just not a good fit for this.

**Comment by parrt** [comment]
Hi, guys. fascinating! I'm going to close as this is more limitation than bug. thanks!
