### ISSUE TITLE
Antlr generates incorrect code when there are no tokens in the input

### ISSUE THREAD

**Issue by teverett** [antlr/antlr4#1214]
Please see:

https://github.com/antlr/grammars-v4/issues/397

This can be fixed on the antlr4 tree in the file antlr4\tool\resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg, at line 891

```
    <if(lexer.tokens)>
    public static final int
        <lexer.tokens:{k | <k>=<lexer.tokens.(k)>}; separator=", ", wrap, anchor>;
    <endif>
```

**Comment by parrt** [comment]
This results from running ANTLR on a file meant only as an import:

```
lexer grammar L;
fragment X : ... ;
```

**Comment by kenzierocks** [comment]
I'm curious, what is the intended workaround for this problem? I have shared `fragment` definitions between my grammars, and this prevents me from building everything because the `import`-only file doesn't compile.

Right now I'm adding a dummy token that can't match anything, but this feels like the wrong thing to do.

**Comment by parrt** [comment]
That would work. sorry I don't have to "fix" this.

**Comment by kenzierocks** [comment]
Okay. Do you know if there would be a noticeable performance impact from doing something like this:
```antlr
DUMMY: . {false}? ;
```

**Comment by parrt** [comment]
i'd take out the predicate but shouldn't ever be invoked.
