### ISSUE TITLE
Python runtime has exponential execution time with some recursive rules

### ISSUE THREAD

**Issue by ProRealTime** [antlr/antlr4#1217]
Hello

The following grammar exhibit a difference in the behaviour between the java and the python runtimes.
The java runtime has a linear (thus fast) parsing time while the python runtime goes up to taking minutes and gigabytes of ram to parse the same code.
The grammar is attached to this bug report.
[demo.g4.txt](https://github.com/antlr/antlr4/files/327207/demo.g4.txt)
[nonkeyword.g4.txt](https://github.com/antlr/antlr4/files/327208/nonkeyword.g4.txt)

The code to parse is quite simple (this grammar is a simplification of the real grammar of course to just show this bug) : 
`output = Max(input1, max(input2, max(input3, max(input4, max(input5, max(input6, max(input7, max(input8, max(input9, max(input10, max(input11, max(input12, max(input13, 42)))))))))))))`

Each added max(inputN, …) double the parse time with the python 2 and python 3 runtimes.

Commenting a single grammar rule stops this behaviour : 
` | atom '[' expression ']' `
Without this rule, there is no more recursion and thus the python runtime bug is no longer visible.
I'm trying to find out the root of this issue, but I can not guarantee I will find it given my lack of knowledge of your runtime code.

**Comment by ericvergnaud** [comment]
Hi,

thanks for this, I’ll look into it.

Eric

**Comment by ProRealTime** [comment]
Hi

Thanks for the quick answer. So far, I've found that it goes exponentially in atn.ParserATNSimulator.computeReachSet (called by computeTargetState).
By looking at the code, I found no obvious reason for that behaviour so far, but I'll keep looking.

**Comment by ProRealTime** [comment]
It is possible to fix the grammar to work around this issue, by removing the `atom '[' expression ']'` rule and replacing the simple `atom` rule by `atom ('[' expression ']')?`. But such a workaround may not be possible for other cases, and the performance penalty may still occur in some other cases.

**Comment by ericvergnaud** [comment]
Thanks. The Java, Python and JavaScript runtimes have the same algorithm, so they should have the same bugs ;-)

**Comment by ProRealTime** [comment]
Well, the Java runtime does not have this issue… I've compared the code and found no obvious difference in the hot code, and since we already saw such an issue in the past (issue 1010), I thinks there is an issue in the Python runtime.

**Comment by ericvergnaud** [comment]
You didn’t notice my smiley

**Comment by ProRealTime** [comment]
Ho sorry

**Comment by ericvergnaud** [comment]
Mmm...
using the below grammar, simplified from yours, focused on recursion:
`
grammar Grammar;

expression: 
	atom
	| atom '[' expression ']' 
	;
	
atom:
	'(' expression ')'
	| mathematical
	| variable
	| constant
	;
	
mathematical:
	'MAX' '(' expression ',' expression ')'
	;
	
variable: 
	IDENT
	;
	
constant:
	NUMBER
	;
		 
IDENT: (LETTER) (LETTER|DIGIT)*; 
NUMBER: (DIGIT)+ (DOT (DIGIT)+)? | DOT (DIGIT)+;
WS: [ \n\t\r] -> skip;

fragment DOT    : '.';
fragment DIGIT  : '0'..'9';
fragment LETTER : 'a'..'z'|'A'..'Z';

`
and the same above input, parsing 10 times in Python3 calling expression(), I get the following times:
0:00:00.004179
0:00:00.000325
0:00:00.000305
0:00:00.000301
0:00:00.000293
0:00:00.000295
0:00:00.000345
0:00:00.000392
0:00:00.000326
0:00:00.000341

except from the first initializing pass, the above times are sub millisecond, so not sure the issue lies in recursion

**Comment by ericvergnaud** [comment]
mmm...
actually, using a simplified grammar focused on recursion:

grammar Grammar;

expression: 
	atom
	| atom '[' expression ']' 
	;
	
atom:
	'(' expression ')'
	| mathematical
	| variable
	| constant
	;
	
mathematical:
	'max' '(' expression ',' expression ')'
	;
	
variable: 
	IDENT
	;
	
constant:
	NUMBER
	;
		 
IDENT: (LETTER) (LETTER|DIGIT)*; 
NUMBER: (DIGIT)+ (DOT (DIGIT)+)? | DOT (DIGIT)+;
WS: [ \n\t\r] -> skip;

fragment DOT    : '.';
fragment DIGIT  : '0'..'9';
fragment LETTER : 'a'..'z'|'A'..'Z';

and parsing the same input 10 times, I get the following parse times:
0:00:22.759969
0:00:00.008795
0:00:00.013012
0:00:00.010250
0:00:00.008912
0:00:00.008791
0:00:00.014304
0:00:00.008682
0:00:00.008973
0:00:00.008944

so the issue seems to reside in the initial build of the DFA/ATN

**Comment by ericvergnaud** [comment]
changing the recursion depth, from 1 to 15, indeed reveals the issue.
In Python:
0:00:00.008589
0:00:00.007482
0:00:00.011429
0:00:00.019264
0:00:00.037562
0:00:00.075797
0:00:00.150463
0:00:00.317070
0:00:00.622716
0:00:01.290880
0:00:02.634988
0:00:05.631027
0:00:11.730704
0:00:23.818153
In Java (using System.nanoTime)
81553000
2329000
2612000
2832000
2830000
2867000
3065000
3177000
3334000
3236000
3407000
3840000
3972000
3981000

**Comment by ProRealTime** [comment]
Thanks a lot, I confirm this fixes the issue.
