### ISSUE TITLE
Lexer members in JavaScript target

### ISSUE THREAD

**Issue by Katona** [antlr/antlr4#1313]
Consider the following lexer grammar:

```
lexer grammar TestLexer;

@members {
    var member = 0;
}

TEST_RULE
    : 'TEST'
    ;
```

This generates `member` as a global variable so it keeps the state between different invocations of separate lexer instances which causes problems. As a workaround, I put the desired variable onto the lexer instance dynamically before using it, like:
```
 if (!this.member) { this.member = 0 }
```
Is there a better solution?

**Comment by ericvergnaud** [comment]
Hi,
not at this point.
'this' in JavaScript behaves very differently from Java or C#, so it would be hard to reach that member from where you need it (i.e. a rule context).
fortunately, with dynamic languages it is not blocking
also the preferred strategy is to use listeners/visitors rather than embed code in the grammar.
Eric

**Comment by Katona** [comment]
Ok, thanks. I use listeners, unfortunately I am using one variable for calculating when to switch lexer modes. Maybe I should try to get rid of that.

**Comment by ericvergnaud** [comment]
Ok,
for this scenario, best is to derive your parser using the superClass option
then in your grammar you can use $parser to refer to the current parser/lexer instance
(I have not tried this with a derived lexer though°
Eric
