### ISSUE TITLE
allow for rule context members

### ISSUE THREAD

**Issue by langit** [antlr/antlr4#134]
As I have noticed, in ANTLR 4, there is a parser rule context class created for each rule. Consequently, a rule ALWAYS returns an object of its corresponding parser rule context class. Thus I find the keyword `returns` misleading. On the other hand, the keyword `locals` is also quite misleading for it seems to mean variables local to the rule's method. The truth is, things declared in `locals` are actually members of the parser rule class, and they seem to be semantically identical to things declared by `returns` (which seem to be an indicator of unnecessary complexity by design). Therefore, I would like to suggest the `@members{ }` action in a rule to inject members into the parser rule class. This would even allow defining new member methods in the class, which would be very cool.

A short example might make the point clear cross:

```
grammar RuleMember;

rule 
@members{
    int ival;
    void method(){  }
}
: (body += stmt)+
| 
;
```

**Comment by AsimNaveed1984** [comment]
Hi Parrt, hope you are doing good. I need your guidance and help, we are using antlr3 for our SQL parsing and SQL conversion by changing AST tree's i.e CREATE FUNCTION will be changed to CREATE PROCEDURE sql construct, we are doing this and have issues what we are now trying to add some weight age to each node in AST and store that node information in Session hashmap.

So we need a unique identifier for each node of AST to mapp over as Key in hashmap. And we have an algorithm that generates unique ids for us how can we add this for each node in AST so that we will be inserting that unique in hashmap as key. OR ANTLR gives some unique identifier for each AST node to identify or point it in AST?

Need your thoughts on this issue please. 

Thanks

Best Regards
Asim Naveed

**Comment by KvanTTT** [comment]
You can use text span as a unique identifier of AST.

**Comment by AsimNaveed1984** [comment]
Thanks KvanTTT, We are using Text but the issue is we can have multiple nodes with same Text such as  PARENTNODE -> SELECTNODE -> FROMNODE -> SELECTNODE, we want to assign individual unique identifiers to them, like first SELECTNODE  has id=2, second SELECTNODE has id=4. Using these ids we can map then AST nodes to its hashmap keys value pairs. I checked ANTLRWORKS it do something like i want in GrammarAST which is extends CommonTree.

public class GrammarAST extends CommonTree {
    static int count = 0;
    public int ID = ++count; // unique identifier per AST node
    ...
}

**Comment by KvanTTT** [comment]
I've written about TextSpan, not Text. TextSpan has start position and length.

**Comment by AsimNaveed1984** [comment]
Oh sorry i thought it was Text. So how can we use TextSpan, can u share some example with me it will really help me a lot. I appreciate your time and help you are giving.

**Comment by KvanTTT** [comment]
Firstly, check what is [Roslyn's TextSpan](https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview#spans).
Secondly, you can check serialized ust with text spans in our [PT.PM](https://github.com/PositiveTechnologies/PT.PM) project: [empty-try-catch.php.ust.json](https://gist.github.com/KvanTTT/b58d2b67b2e2b4906d1d7fedf0a6de98).
