### ISSUE TITLE
travis now failing due to too many tests causing timeout for osx but linux is ok still

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1385]
For example https://travis-ci.org/antlr/antlr4/jobs/177752866#L3191

**Comment by parrt** [comment]
@mike-lischke i think you added "sudo required" to the travis build which i think is slower. The parallel thing didn't seem to help but I'll try again. is that sudo really needed? Why is g++-5 listed as required btw?

**Comment by mike-lischke** [comment]
That's what I mentioned in e-mail before already. You will soon hit that limit and with every target you add things become worse. No, I didn't add `sudo required`. In fact I tried to get rid of it, but ran into other weird problems then. When you do a blame, you'll see Eric added that line in revision [14ade86] and without it some installations with sudo fail.

But I believe that sudo setting is not the true culprit, and I doubt that removing it will improve the situation dramatically. There are other problems that have a stronger effect:

- The maven setup takes several minutes on its own, before the tests even can start. There are a **many** downloads happening (also because Travis CI doesn't cache anything).
- For each test an own test application is compiled. This is especially costly for language which rather spend time with app creation, in order to get better execution speed.
- The test execution is too linear. It doesn't fully utilize the provided resources (e.g. CPUs).
- The tests are triggered each individually by a Java class, which causes delays because of the many domain switches (Java <-> external processes).

Here a few ideas to improve this situation:

1. Only execute a subset of all test on CI (this might be the easiest way).
2. Group tests in a way that they can run with a single executable (I suggested this already before). This will avoid frequent test binary creation.
3. Don't run each test individually from Java but find a way to let a target run all the tests on its own. Together with 2. this will significantly speed up the process.
4. Run more tests in parallel.

And for the `g++5` setting. I believe this is used by cmake, but I'm not 100% sure (not my field of expertise). I added that to make the runtime library creation succeeding and then didn't touch it anymore when I continue with the actual tests. Might be you can just remove it and cmake will use clang then. Don't expect any speed improvement from that, though.

**Comment by ericvergnaud** [comment]
Hi,

what we need is this: https://github.com/travis-ci/travis-ci/issues/4090 <https://github.com/travis-ci/travis-ci/issues/4090>
but looks like it’s not going to happen soon…

in the meantime we could use:

env:
	- TARGET=java
	- TARGET=csharp
	etc…

to populate a build matrix
we could then use $TARGET in the build script to only install the required components and run the corresponding tests

Eric

**Comment by mike-lischke** [comment]
Are builds in a build matrix distributed over multiple containers? If not then I don't see how this would help as still all tests would run in a single container and need more or less the same time to execute.

**Comment by ericvergnaud** [comment]
yes they are, that’s the whole point of a build matrix

**Comment by parrt** [comment]
Hi. Yep, it is splitting off the os x builds now but for some reason that "machine" is so slow that it times out consistently. I did turn off cpp for os x build.

appveyor is infinitely faster and has no problem cranking through these tests I notice.  Oh, it doesn't seem to do C++. odd. See https://ci.appveyor.com/project/parrt/antlr4/build/4.6-SNAPSHOT+AppVeyor.12   Maven *should* run cpp tests because this is what is executed:

```
mvn install -q -Dantlr-python2-python="C:\Python27\python.exe" -Dantlr-python3-python="C:\Python35\python.exe" -Dantlr-javascript-nodejs="C:\Program Files (x86)\nodejs\node.exe" --batch-mode
```

**Comment by parrt** [comment]
Fixed. see https://travis-ci.org/antlr/antlr4/jobs/178089136

**Comment by mike-lischke** [comment]
Hmm, but it's still close to the timeout limit. Add another target or a couple new tests and you might hit it again.

**Comment by parrt** [comment]
yeah, no doubt.  I removed all but swift from os x target.
