### ISSUE TITLE
[Tool]How to generate a file per each child ParserRuleContext

### ISSUE THREAD

**Issue by gaulouis** [antlr/antlr4#1456]
Hello,

I have read the StringTemplate documentation, Target.java, CodeGenPipeline.java, CodeGenerator.java, OutputModelController.java, CodeGeneratorExtension.java

Despite all my efforts I can not find what I need to do.

In Target.java, I have added
```
public boolean isOneClassPerFile() {
	return false;
	// overrided in CTarget.java by : 
	// getTemplates().getInstanceOf("oneClassPerFile").render().equals("True")
}
```
In CodeGenPipeline.java::process(), I have added:
```
ST ruleContext = gen.generateRuleContext(true);// Duplication of gen.generateParser(true)
gen.writeRuleContext(ruleContext, true);
```

In CodeGenerator.java, I have added:
```
public void writeRuleContext(ST outputFileST, boolean header) {
	if (getTarget().isOneClassPerFile()) {
		// TODO:
		// for each rule function
		//	if (gen.getTarget().needsHeader())
		//		getTarget().genFile(g, outputFileST, "XXX-context.h");
		//	getTarget().genFile(g, outputFileST, "XXXX-context.c");
	}
}
```

Any help would be appreciated.

**Comment by mike-lischke** [comment]
I believe that is impossible to implement without a big refactoring of the generation code. And IMO the benefit is questionable. Keep in mind you might end up with hundreds of files then (in my current parser I have 500 rules, each would create 2 files then). There won't be any compilation speedup either, since all files would always be created at the same time. And I can imagine that you might get circular inclusion problems. Honestly, not the best idea IMO.
