### ISSUE TITLE
heading towards 4.6 release

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1482]
@antlr/antlr-targets Howdy! Ok, I'd like to finish up 4.6 in the next week. What remaining issues must be fixed for 4.6? Are you satisfied people know how to use your target (i.e., via the doc)?  Maybe add a comment here with a link to issue or issues you feel must be in 4.6 release. Silence implies consent to release 4.6 :)

**Comment by parrt** [comment]
For Java, I want to fix:

* [ ] https://github.com/antlr/antlr4/issues/1036
* [ ] https://github.com/antlr/antlr4/issues/1175
* [ ] https://github.com/antlr/antlr4/issues/1042
* [ ] https://github.com/antlr/antlr4/issues/1007

**Comment by ericvergnaud** [comment]
Hi,

still working on implementing the closure loop early exit optimisation for C#
Not sure I will be done by next week.

Eric

**Comment by mike-lischke** [comment]
I'm also still working on this fix. While it improves speed a lot in some special cases, I have hit a wall with one test case where parsing never ends because of extremly much comparison going on which slows down the project. No idea when I can fix that.

@parrt Once 4.6 is out how long will it take for a follow up release (e.g. when I have new changes in the C++ target)? Do you have a fix release cycle or rather do a new one when necessary?

**Comment by parrt** [comment]
Can you @antlr/antlr-targets guys check https://github.com/antlr/antlr4/blob/master/doc/releasing-antlr.md to ensure I know how to properly release your target? I guess we need Go, Swift notes and others can check the text for accuracy. (Email me changes to avoid collisions)

**Comment by parrt** [comment]
@mike-lischke I can do a 4.6.1 soon if you like. I have no fixed release cycle but it appears to be 2x per year at moment if I'm left to my own behavior (i.e., without nudging from you guys)

**Comment by mike-lischke** [comment]
About release notes: you have to uncomment the last line in each C++ deployment script (mentioned in the docs) and update the path where you want the final packages be copied.

About release dates: well, I don't wanna hold the major 4.6 release with my smaller changes and I have no idea how long it will take till I can find the problem with the left recursion test. This can then be delivered in a follow up release. Btw, can you merge the threading fix I posted today? This could then be tested more before release.

**Comment by parrt** [comment]
@janyou You say just "*You will find Swift runtime (framework project) in antlr4/runtime/Swift*" on https://github.com/antlr/antlr4/blob/master/doc/swift-target.md  but what does that mean? They must go to github or something? Do I supply a zip? jar? tar? How do I publish a swift release for antlr? @hanjoes can you help?

**Comment by parrt** [comment]
@antlr/antlr-targets I'm stuck doing admin work most of day today but will be back in action soon as possible.

**Comment by hanjoes** [comment]
I presume the old doc implies package structure in @janyou's original repo, but yeah, I will take a look.

**Comment by janyou** [comment]
@parrt I think Swift runtime and CSharp runtime are similar.

> [CSharp](https://github.com/antlr/antlr4/tree/master/runtime/CSharp)
> Step 3: Add a reference to the ANTLR runtime in your project
> We trust that you know how to do this :-).

**Comment by parrt** [comment]
I don't. What do you mean add the run time? Do you mean add a zip file? Add a directory to a path? If you want me to distribute your target you have to tell me what to deliver.

**Comment by ewanmellor** [comment]
@parrt Janyou means that you'd just import the ANTLR runtime as a project inside Xcode.  In other words, a source-level import.  There's no distribution to do, per se, other than what's already on GitHub, because all the project files are already there.

It's pretty normal to do this with Swift, because there's no binary compatibility between Swift versions (yet) so there's little value in distributing compiled binaries for open-source projects.

There are package managers (Swift Package Manager, CocoaPods, or Carthage) but they'd only add  a thin bit of metadata over what's already here, and it's purely optional.

**Comment by hanjoes** [comment]
I think by offering some kind of "artifact" could make the usage easier and cleaner. And since we may not be able to assume that every user will like to statically link the parser into their product, by offering a library will result in more flexibility in the future.

**Comment by ewanmellor** [comment]
@hanjoes Distributing "artifacts" doesn't make sense for Swift (compared with Java for example) because the ABI for Swift is not stable yet, so you have to have a perfectly matching Swift standard library.

Swift doesn't have the same library system that other languages have, so the distinction between static and dynamically linking into your product doesn't have the same connotations that it does elsewhere.

What you have in the tree is *already* a library (technically, a framework in Apple's terminology).  Distributing them as source code (with an Xcode project file) is entirely normal.

**Comment by hanjoes** [comment]
That makes sense. I guess for swift the common practice is to distribute it with the source code so user can add the xproject into workspace and use the framework generated. Haven't played with package yet but right now the closest way seems to publish a CocoaPod but that seems require a separate repo which is basically same as source level distribution.

**Comment by janyou** [comment]
@ewanmellor @hanjoes @jeffreyguenther 
I'm going to be very busy the next few months. I hope you take over the support of Swift target.
If you have any questions, you can send mail to me.
(#1439 hasn't been solved yet)

**Comment by hanjoes** [comment]
I will have more time when it’s approaching to holidays.
Also submitted an issue #1514 since Swift codegen is not working right now.
Fix would be easy but we need to decide whether we want to use 3rd party library for JSON serialization.

**Comment by parrt** [comment]
@ewanmellor @hanjoes So should i change doc to say "download the repo and look in runtime/Swift"?

**Comment by parrt** [comment]
@antlr/antlr-targets Any showstoppers or can I release?

**Comment by parrt** [comment]
Currently appveyor fails on C++ but linux/mac work. says:

```
...
CMake Error at CMakeLists.txt:101 (message):
  Your C++ compiler does not support C++11.
can't compile antlr cpp runtime
C++ runtime build succeeded
ln: failed to create symbolic link './libantlr4-runtime.so': No such file or directory
In file included from C:\Users\appveyor\AppData\Local\Temp\1\BaseCppTest-main-1481744646888\M.cpp:5:
C:\Users\appveyor\AppData\Local\Temp\1\BaseCppTest-main-1481744646888/M.h:7:10: fatal error: 'antlr4-runtime.h' file not found
#include "antlr4-runtime.h"
         ^
1 error generated.
...
```

Any ideas?

**Comment by hanjoes** [comment]
@parrt, yes. we cannot bypass the source code. There are a few details people can follow to import the xcodeproj I would like to put into the doc today after work but if you are about to release it we can just do a quick tweak and more details for the doc could come later.

**Comment by parrt** [comment]
@hanjoes I'll wait til tomorrow. no sweat! I'm stuck doing admin work now for 3 hours anyway.

**Comment by hanjoes** [comment]
ok!

**Comment by ericvergnaud** [comment]
None here

Envoyé de mon iPhone

**Comment by parrt** [comment]
@antlr/antlr-targets Whew! I think that I have pulled in all of the PRs and fixed all of the issues for 4.6. I'm going to create the release notes now and deploy to mvn central another snapshot. Let's see if anybody complains before we release. Thanks again for all your hard work people!

**Comment by pureconfig** [comment]
@parrt Excellent news! How long does it typically take for the IntelliJ plugin to catch up? I'd like to see 4.6 support there as well (C++ target!)

**Comment by parrt** [comment]
I hope to get plugin out shortly.
