### ISSUE TITLE
Please, remove lexer from Antlr

### ISSUE THREAD

**Issue by dims12** [antlr/antlr4#1527]
I suggest to remove lexer completely in next versions of Antlr.

Lexer is just bad-designed and feature-limited parser, that runs in the first pass.

I suggest to allow multiple passes of multiple parsers and remove lexer as is.

Missed functions, like characted regions and regular expressions, should be moved to parser.

**Comment by sharwell** [comment]
The flexibility of the lexer is an area I would like to see improved in a hypothetical ANTLR 5. That said, it's important to remember that the current lexer design is driven by a goal of maximizing performance of character-level parsing in the most common user scenarios. For most users, the lexer feature set is sufficient for tokenizing input. If we are not careful, introduction of more power in lexing (e.g. scannerless parsing) could easily result in a tremendous and unnecessary performance limitation for all the existing users who are making use of the current lexer functionality.

**Comment by dims12** [comment]
Okay, but can we make lexer disablable then? If you want performance, you turn it on. And let it be default for compatibility. But if you want smarter parser, you turn it off and rely on parser only. But still re-implement lexer methods inside parser, for ex characted ranges.

**Comment by sharwell** [comment]
@dims12 Your question may already be answered by @parrt between #1107 and #814. I would suggest reviewing the comments there and then wording your proposal as something very specific if you are proposing something different.

**Comment by parrt** [comment]
Yeah, scannerless ANTLR parsing is no problem. I forgot to add to latest release. See https://github.com/antlr/antlr4/issues/814 per @sharwell In other words, this is a duplicate request. You don't need a lexer at all.

**Comment by cleishm** [comment]
If scannerless ANTLR parsing is no problem, how do I, for example, write a rule that matches a sequence of any characters excepting, say, digits?

With a lexer:

```
rule = (~DIGITS)*;
DIGITS : [0-9];
```

I can't do this with just parser rules (short of listing every possible character _except_ digits):

```
rule = (~digits)*; // error: negation not supported
digits : '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';
```

This example is contrived, but I have real examples where I'd love to remove the lexer, because individual chars have different meaning depending on context, and yet I need to be able to negate groups.

**Comment by ericvergnaud** [comment]
The issue does not lie with the Lexer, rather the need for the Parser to rely on a stable list of next tokens in order to make decisions 
For this, input has to be consumed.
The way around this is to have a Lexer rule per character with varying meaning
Appreciate this is only workable if the above set of characters is very limited 

Envoyé de mon iPhone

**Comment by cleishm** [comment]
Hey @ericvergnaud! Thanks for the reply.

I understand it's not an issue with the Lexer. My point is that `CharsAsTokens` (#814) doesn't really address the desire for scannerless parsing, as this shortcoming in the parser is substantial enough to render many real-world use cases impossibly difficult to implement.
