### ISSUE TITLE
C++ target - remove dynamic_cast slowness?

### ISSUE THREAD

**Issue by pureconfig** [antlr/antlr4#1535]
I'm happy with the new C++ target, with some help I even got the CLion plugin working. The GUI should mention "Cpp" as the target name though, I had to guess (it mentions the other ones) and "cpp" didn't work because of casing.

But hey, it's awesome.

Trying to figure out how to get closer to Antlr3 performance though. Profiling shows that a fair bit is spent in dynamic_cast various places.

@mike-lischke Maybe replace these with LLVM-style RTTI casts? (they did it exactly because c++ rtti is quite slow)

**Comment by pureconfig** [comment]
Also, the parser keeps generating lines like

    TParser::ExprContext *previousContext = _localctx;

where previousContext is never used afterwards. Optimized out, but worth mentioning.

**Comment by pureconfig** [comment]
After more profiling, dynamic_cast is responsible for 8% of the execution time, _add_shard / _release_shared() 10%

I believe the shared ptr issue is known, but the dynamic cast is fairly nasty as well. It adds up.

**Comment by mike-lischke** [comment]
Best is to measure time for warmup and follow up parsing separately, because the warmup phase is consuming a lot more time and is building structures that are cached for later reuse. Easier to consider them separately.

The dynamic casts are modeled after Java (actually the type checks). Some can probably change so that type fields are checked instead (e.g. for transitions and states). Any change must be platform agnostic however. So, something like that LLVM-style is probably not a good choice.

Shared pointers are pointer indeed, but I have no better idea yet for memory managment. There are **many** intermediate instances for ATN configs etc. which must be released as soon as they are no longer needed or we end up with 1GB+ memory consumption.

I believe it would help to make the highly recursive closer* calls in the ATN simular into iterations. Would also help for highly nested expressions. Not sure how much this will bring in terms of execution speed.

About the generated code: you don't know if there is a scenario where this is needed. This is always a problem with generated code. Similar for the type casts there. Often a context is casted even though it already has the right type. But there could be situations where this is not the case. We cannot predict that.

**Comment by pureconfig** [comment]
> Any change must be platform agnostic however. So, something like that LLVM-style is probably not a good choice.

I'm talking about the C++ implementation of LLVM, hence it's platform agnostic (they're just C++ templates after all)

http://llvm.org/docs/ProgrammersManual.html#the-isa-cast-and-dyn-cast-templates

**Comment by mike-lischke** [comment]
But those LLVM templates don't work in VC++, right?

**Comment by pureconfig** [comment]
@mike-lischke sure they do, I build llvm + clang on Windows all the time

**Comment by mike-lischke** [comment]
But Visual Studio doesn't use LLVM. You cannot force all users of ANTLR to use LLVM.

**Comment by pureconfig** [comment]
@mike-lischke Not sure if I'm unable to convey a simple message or if you're trolling me :)

I compile LLVM using VISUAL C++. LLVM has nothing to do with anything, except that they implemented their own RTTI. 

WHICH COMPILES IN VISUAL C++ AND ANY OTHER CONTEMPORARY C++ COMPILER.

Caps off.

**Comment by mike-lischke** [comment]
OK, please teach me. Can you give me a simple example app that I can compile with a standard Visual Studio 2015 installation? Doesn't need to use ANTLR, anything will do that shows the use as you propose here.

**Comment by pureconfig** [comment]
Sigh

**Comment by pureconfig** [comment]
I'm clearly unable to explain this. Closing.

**Comment by mike-lischke** [comment]
The original issue still stands. If dynamic_casts are so expensive we should do something about it. But instead of lowering their impact we could simply try to avoid them at all. I have a few ideas for this and will pursue them in the comming weeks.

**Comment by jimidle** [comment]
Mike,

Just take the time to optimise in your own time mate. Anyone saying:

"Sigh"

didn't think about all the effort you have put in so far. I'll try to make some time to help on the optimisations without sighing at you ;)

Jim

**Comment by pureconfig** [comment]
> didn't think about all the effort you have put in so far. 

@jimidle Bullshit. I have given Mike a lot of positive feedback, and I'm donating to Antlr because of the Cpp backend. 

I spent considerable time myself going through Mike and Dan's code, profiling and verifying to make sure my grammar still works. 

What I'm sighing at is my inability to explain how LLVM's RTTI mechanism would also work in Antlr.

Feel free to stand corrected.

**Comment by mike-lischke** [comment]
Yes, true, I got very good feedback from you @pureconfig, you just gave up too quickly when I failed to understand the scenario you have in mind and ask for a demo that makes it clearer to me. It's just that VC++ and LLVM are 2 totally different compiler infrastructures (like gcc and clang), so, if you use VC++ to compile your code you are nowhere bringing in LLVM. Using LLVM to compile means you don't use VC++. And all I say is that I cannot force people to use LLVM (even though they could). Hence a solution for this dynamic_cast problem must be something we can compile everywhere (keep in mind on Linux many use gcc, so the same problem exists there).
