### ISSUE TITLE
Do not disable CS4127 when compiling C++ target with MSVC

### ISSUE THREAD

**Issue by sharwell** [antlr/antlr4#1550]
Currently **antlr4-common.h** disables CS4127 when compiling with MSVC. This is due to the use of `while (true)` in the C++ code, which is not idiomatic C++. Each use of `while (true)` should be replaced with `for (;;)` in the runtime library code and code generated from templates, which is idiomatic C++ that does not produce the previously indicated warning.

:memo: In debug builds with MSVC, the `for(;;)` actually even produces smaller code (more of a trivia item, but still interesting).

**Comment by mike-lischke** [comment]
I can't follow. In what sense is `while (true)` not "idiomatic"? It's a totally valid C++ construct and doesn't cause warnings in any other compiler than VS 2015.

**Comment by sharwell** [comment]
@mike-lischke It's a holdover from very old compilers which weren't able to optimize away the literal `true` value. The current MSVC compiler continues to leave the literal evaluation in place in debug builds. In the end, the form `for (;;)` is at least as recognizable to C++ developers as `while (true)`, and eliminates the warning at the source.

**Comment by mike-lischke** [comment]
Sorry if I show so much reactance here, but I don't see why I should adjust to the compiler for totally valid code, instead of the other way around. The compiler is wrong, so I shut it up. And `for (;;)` is semantic nonsense from the oldest ages of C. It's meant to iterate over a range, but this form has no range. For no-range loops with have other syntactic means (while-do, do-while, repeat-until). And again, it's only one compiler of several which complains (and not the first warning from MSVC we see, that is completely useless).

I'm not convinced to change this part, sorry.
