### ISSUE TITLE
Support importing multi-mode lexer grammars

### ISSUE THREAD

**Issue by sharwell** [antlr/antlr4#160]
Note that specific semantics for this feature have not yet been established.

**Comment by mar9000** [comment]
Not, with this addition I get this exception (I'm extending ANTLRv4Lexer).

> Exception in thread "main" java.util.EmptyStackException
	at org.antlr.v4.runtime.Lexer.popMode(Lexer.java:216)
	at org.antlr.v4.runtime.atn.LexerPopModeAction.execute(LexerPopModeAction.java:82)
	at org.antlr.v4.runtime.atn.LexerActionExecutor.execute(LexerActionExecutor.java:193)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.accept(LexerATNSimulator.java:395)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:328)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:259)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:143)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:165)

Another difference is that my lexer gets a method NESTED_ARG_ACTION_action() that ANTLR lexer does not have.

**Comment by zhaohuiyang** [comment]
Could anyone please share an update on this issue?

**Comment by parrt** [comment]
Hmm..Unfortunately I'm not going to be able to get to this for the next 4.5.1 release

**Comment by TheEricWilson** [comment]
If the modes are not in the thing being imported, but only in the part doing the import would that work?

**Comment by parrt** [comment]
Actually, you don't need to import a lexer. Just use it as a separate lexer g4 file, right?

**Comment by TheEricWilson** [comment]
Yes the wording of several things seems to imply to me that I can not do includes if I have modes in my lexer.

**Comment by parrt** [comment]
Well, it's true, no includes of modes but it's easier to not import the lexer into the parser. just use as separate file. I'll close for now.

**Comment by TheEricWilson** [comment]
I am trying to import modes into a lexer and not the parser

**Comment by parrt** [comment]
ah. ok, reopening.

**Comment by may-bee** [comment]
Thinking out loud about the semantics of this feature:

* imported tokens/rules/named actions of the default state will be appended to the root grammars default state at the bottom
 * tokens/rules of modes of imported grammars will _not_ be appended to the root grammars default state as it is currently the case.
* imported modes will be added as long as there is 
 * no name conflict of any root grammar mode or (transitively) imported mode.
 * no name conflict of any two token/rule, which is defined within any mode
 * otherwise an error is thrown

Restrictions:

* There is no way of "enriching" modes by describing tokens/rules in an imported grammar mode carrying the same name as a node in the root grammar

I currently do not see any use case, where the mentioned restriction might be a major drawback.

**Comment by rossy62** [comment]
I found this thread via a Stackoverflow from sharwell.
For a newbie, I was trying to separate lever grammar and parser grammar by maintaining two separate files and importing the lexer into the parser grammar .g4.  If there is another multi-file approach, say using a .g4 lexer no .g4 parser, what mechanism is used to define external tokens declared by the lexer .g4 file to the parser?  Does th antlr4 tool accept multiple .g4 files on the command line?
(probably need to re-read all the command options)
I

**Comment by cdemian20** [comment]
I think it would be more flexible if modes could be enabled/disabled on an individual basis, the resulting mode being combined from all active modes. This would make possible 'modifier' modes with only a few rules that apply in addition of already existing rules.

Modes from imported grammars could be combined into the main grammar from all modes with the same name from all imported grammars.

Eventually it may be needed to support modes for parser (and combined) grammars too.

**Comment by parrt** [comment]
Resolved by https://github.com/antlr/antlr4/pull/2135
