### ISSUE TITLE
[Cpp] compilation warning 

### ISSUE THREAD

**Issue by john30** [antlr/antlr4#1619]
Before submitting an issue to ANTLR, please check off these boxes:
 
- [X] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [X] I have done a search of the existing issues to make sure I'm not sending in a duplicate

When compiling the C++ target on an Ubuntu 14.04 64Bit I get the following compiler warning:
```
[ 51%] Building CXX object runtime/CMakeFiles/antlr4_static.dir/src/UnbufferedCharStream.cpp.o
/home/john/ebus/grammar/runtime/runtime/src/UnbufferedCharStream.cpp: In member function ‘virtual size_t antlr4::UnbufferedCharStream::fill(size_t)’:
/home/john/ebus/grammar/runtime/runtime/src/UnbufferedCharStream.cpp:55:50: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if (_data.size() > 0 && (size_t)_data.back() == EOF) {
                                                  ^

```
This seems to be an error, because the EOF check will never be really performed.
g++ version is this: (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904

**Comment by gaulouis** [comment]
Hello,

I'am not really sur, but may be, this modification can guid you?
` basic_string<size_t> ` instead of [u32string](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/runtime/src/UnbufferedCharStream.h#L58) in concordance with the [EOF](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/runtime/src/IntStream.h#L30) declaration

See the [documentation](http://www.cplusplus.com/reference/string/u32string/): 
``
typedef basic_string<char32_t> u32string;
``

Best regards

**Comment by john30** [comment]
@gaulouis how is that supposed to help?
the compiler warning just needs to be treated correctly

**Comment by mike-lischke** [comment]
This is a weird warning, given that EOF is declared as a size_t type (see IntStream::EOF). However, maybe the compiler uses a wrong EOF symbol at this point? Can you try with explicit qualification and/or see what EOF is used there?

**Comment by jasonar81** [comment]
In IntStream.h: change 
static const size_t EOF = (size_t)-1;
to
static const size_t EOF = std::numeric_limits<size_t>::max();
and #include <limits>

**Comment by mike-lischke** [comment]
... and #include what? :-)

**Comment by jasonar81** [comment]
NM that post.  I thought that fixed it, but I wasn't paying attention properly.

The issue is that back() on the u32string can never return a value more than 0xFFFFFFFF, but we are comparing for equality with 0xFFFFFFFFFFFFFFFF.  Obviously it can never be true.  And the compiler tells us this.  I just commented out the if statement.

**Comment by mike-lischke** [comment]
Ah, of course. I was implicitly thinking that the size_t cast would automatically make 0xFFFFFFFF to 0xFFFFFFFFFFFFFFFF. How stupid.

Hower, I'm not sure we should just disable this check. Need to think about it.
