### ISSUE TITLE
Remove generated Swift files or add regression test

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1640]
The path to generated files: https://github.com/antlr/antlr4/tree/master/runtime/Swift/Tests/Antlr4Tests
This issue also related to XPath issue: https://github.com/antlr/antlr4/issues/1620

**Comment by parrt** [comment]
@hanjoes Can we move the test files to an `api` dir under https://github.com/antlr/antlr4/tree/master/runtime-testsuite/test/org/antlr/v4/test/runtime/swift to mirror what java does when testing apis? or maybe remove these?

**Comment by hanjoes** [comment]
Yes we can. but i didn't quite get the expectation for those API tests, should they be running as part of the runtime-testsuite? or something that should run in the languages' own way (for e.g. in swift we do "swift test" which leverages SPM's functionality)? If it's the first case, we can tweak our BaseSwiftTest.java file to generate a whole swift project on-the-fly and test it as part of maven, and if it's the latter case, it's better we put the tests in the runtime, since SPM has this limitation that requires us to put all the stuff together. 

And by removing are we talking about removing the test cases or the generated files?

**Comment by parrt** [comment]
What is the purpose of that specific test?  Is a something that could be handled through the generic Descriptor objects or is this really just testing the API? If API, then let's mirror what we do in Java. You will note that we also have grammar files: https://github.com/antlr/antlr4/tree/master/runtime-testsuite/test/org/antlr/v4/test/runtime/java/api

**Comment by hanjoes** [comment]
The purpose of the tests is for API testing, which is supposed to mirror the tests in the link you mentioned above. I'm more concerned with how we want to run the tests though, do we want to run it with "mvn test" just like we run the runtime-testsuite? Since I thought our wild-west approach for api tests would include running it within the runtime projects themselves.

**Comment by parrt** [comment]
oh right! Duh, we can't move that to runtime testing--that only runs as java. So I withdraw my objection. closing.
