### ISSUE TITLE
Support tree rewriting

### ISSUE THREAD

**Issue by pureconfig** [antlr/antlr4#1732]
While the focus of Antlr4 is unfortunately no longer for compiler/interpreter/transpiler writers, I use it for a transpiler anyway. Antlr4 is so much nicer grammar-wise than Antlr3.

However, the lack of tree rewriting/mutation is driving me crazy. This is for special cases, of course, but when you do need it (say, for normalization), you end up doing ugly duplication on a side-AST.

All I really need is mutators on the generated vector/string fields (this is the C++ backend). I can't even call setText now.

Anyway. Frustrated.

Any plans for tree mutation?

**Comment by mike-lischke** [comment]
Have a look at #1647.

**Comment by pureconfig** [comment]
@mike-lischke I mean the generated context objects I get in visitor callbacks.

**Comment by pureconfig** [comment]
@mike-lischke Anyway, nice to see that work has begun. Do you plan to support this in your cpp target anytime soon?

**Comment by mike-lischke** [comment]
This is basically in the design phase currently. Implementation details are discussed and such. As soon as the dust has settled and the Java impl is done all runtime maintainers will go and port it to their runtimes.

**Comment by pureconfig** [comment]
I see. Thanks.

**Comment by pureconfig** [comment]
@mike-lischke I've been using a cpp target *a lot* by the way. Great quality.

**Comment by mike-lischke** [comment]
Glad to hear :-)

**Comment by millergarym** [comment]
@pureconfig are you building an AST, or as per antlr4 doing everything in the listeners or visitors?

Like you I really like the tree stuff. So much so that I effectively added tree grammars back to antlr4. The reason I say effectively is because it is in "user" space, no hack to antlr4. Basically the listener build an AST using a custom tree data structure that support the token stream interface. The tree is then used as the token source to a different (effectively tree walker) parser. A major difference between this tree structure and antlr's is that it is immutable and importantly the nodes and the tree topology are separate. This allow the nodes to live in multiple trees at the same time, making tree rewrite trivial, much easier the tree write in antlr3.

At the moment I'm prototyping, so not really concerned with performance. There are a number of reason this might not suite your purposes.
- It is by definition multi pass - AST build & walk
- Currently tree write require building a new tree topology. If this is a real issue a change tracking proxy could be written - easier said than done though.

You can find a early version of this the url below.
https://github.com/wxio/antlr4-go-examples/blob/master/eval/ExprWalker.g4
Should be pretty trivial to port to C++.

Let me know what you thing.

**Comment by pureconfig** [comment]
@millergarym My problem is that the input language is simple enough for me to use the generated Antlr context objects as the AST. BUT, because I can't mutate it, I end up with my listener producing an AST, which I then have to visit again. Very frustrating.

**Comment by millergarym** [comment]
@pureconfig ahh, the third dot point
- This solution is over kill for a simple problem ;-)

**Comment by pureconfig** [comment]
@millergarym Exactly :)

**Comment by maybeec** [comment]
@millergarym I was searching for tree walker parsers in antlr4. Thanks!
Can you point me to the implementation? I was searching a little bit in your antlr4 fork, but could not directly find it while following the commits.

I would like to give it a try.

**Comment by millergarym** [comment]
@maybeec take a looking at the link in my earlier comment. There is no ast construction or tree walker in the antlr code, it is done in the client code. In this case Go.

As I mentioned the walker is a parser, will the source token coming from a depth first search of a tree (the ast). The ast is built by a listener to a prior parser. The ast is a custom Go tree, not one provided by antlr.

What is your target language?

**Comment by maybeec** [comment]
@millergarym ok thanks. Got it.
I will have a closer look at it.

My target language is Java as well as the source language. I am looking for the best way of source code transformation with antlr4. There are tools like TXL or Stratego out there, but they do not provide updated Java grammars for real scenarios in practice. I am happy that I somehow can get the latest grammars for free in antlr4. So I want to see my oportunities to transform code using antlr4. Listeners are a little bit unhandy. I will give the tree walker concept a try.

**Comment by parrt** [comment]
Hi guys. i'm going to label as a dup of #1647.
