### ISSUE TITLE
JavaScript target: please add some exports to **/index.js

### ISSUE THREAD

**Issue by ChristophWedler** [antlr/antlr4#1759]
For writing an own error strategy (which is basically essential with unreserved keywords), I need access to the following classes and functions:

*   `antlr4.error.DefaultErrorStrategy`: should be mentioned in `error/index.js` like `BailErrorStrategy`
*   `antlr4.IntervalSet`: should be mentioned in `index.js` like `Interval`
*   `antlr4.LL1Analyzer`: should be mentioned in `index.js`
*   function `antlr4.predictionContextFromRuleContext`: should be probably made a property of `antlr4.ParserRuleContext` (is also closer to the corresponding static method in the Java runtime)

This way, I would have one `var antlr4 = require('antlr4')` in my code.
Yes, currently I can have different `require`s for the above mentioned classes, but that probably will not work anymore if the JavaScript antlr4 runtime is sent through some compressor like https://github.com/mishoo/UglifyJS2 (which would be actually quite cool for the "official" antlr4 NPM package...)

**Comment by ericvergnaud** [comment]
The recommended packaging is to use webpack on the generated parsers/listeners/visitors, so not sure the exports are an issue. I will consider a PR for these.

**Comment by gciatto-unibo** [comment]
This is still an open issue in v. `4.8.0`.

For instance, currently, `DefaultErrorStrategy` is not exported in [`errror/index.js`](https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/antlr4/error/index.js).
This prevents me from implementing two-stage parsing in JS because I cannot properly import the  `DefaultErrorStrategy` class, which is needed in the second stage.

I believe `DefaultErrorStrategy` and other classes were not exported by mistake.
If this is the case, please fix this ASAP: it should be just a minor/patch version number increase.

**Comment by ericvergnaud** [comment]
Hi,
maybe submit a PR?
Eric
