### ISSUE TITLE
UTF-16 code units in antlr 4.7 lexers

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1802]
@bhamiltoncx what happens to legacy grammars that tried to do their own surrogate code unit matching in the lexer grammar? If we do nothing, will they continue to work, assuming users pass in the same `CharStream` implementation as before? Should I add a test in the tool itself looking for UTF-16 markers and emit an error?

**Comment by bhamiltoncx** [comment]
Legacy grammars which did their own surrogate code unit matching will need to continue to use `ANTLRInputStream` until they upgrade to `CharStreams` and remove the surrogate code unit matching.

If they used `UnbufferedCharStream` they are currently out of luck. I assume there are not many clients that intersect both manual UTF-16 parsing and `UnbufferedCharStream` usage. :)

**Comment by parrt** [comment]
I'll add this to the doc to "fix".

**Comment by bhamiltoncx** [comment]
A more important thing to mention is that previously, clients could
directly pass Token.getStartIndex() / Token.getStopIndex() to Java and C#
String APIs (because both used UTF-16 code units as the fundamental unit of
length).

With the new streams, clients will have to convert from code point indices
to UTF-16 code unit indices.

We can provide helper logic to do this, invoked via a Listener:

https://gist.github.com/bhamiltoncx/9282e943efab384220723a0daa37d72e
