### ISSUE TITLE
Should adaptivePredict() evaluate semantic predicates?

### ISSUE THREAD

**Issue by mike-lischke** [antlr/antlr4#1842]
Currently `adaptivePredict()` evaluates semantic predicates and throws a NoViableAltException if it cannot find an alt behind a sempred that is evaluating to `false`. This leads to the effect that `adaptivePredict()` bails out of the parsing process too early and following `FailedPredicateExceptions` never can get thrown. Consider a case like this:

```
math: numericalExpression ('+' | '-' | '*' | '/') numericalExpression;

numericalExpression
: NUMBER | other
;

other:
    ('a' | 'b'+)
    | { false }? String
;
```
For input like `1 + "abc"` it throws a `NoViableAltException` in the `adaptivePredict()` call in `numbericalExpression()` and hence never goes down to `other()` where the failing predicate would trigger a `FailedPredicateException`.  That behavior completely contradicts the intention of `FailedPredicateException`. I have yet to find a case where such an exception is actually thrown, but would expect it to be thrown in all cases where an alternative would match but is blocked by a sempred (and there is no other matching alt).

A possible solution could be that `adaptivePredict()` sees through sempreds like `sync()` does, but that might have unwanted side effects.

**Comment by BurtHarris** [comment]
I recall the "fine print" in https://github.com/antlr/antlr4/blob/master/doc/predicates.md, I assume you already know that.   One section that seems like it might cover your example says:

>The decision in stat can't test those predicates because, at the start of stat, the current token is a left curly. To preserve the semantics, ANTLR won't test the predicates in that decision.
>Visible predicates are those that prediction encounters before encountering an action or token. The prediction process ignores nonvisible predicates, treating them as if they don't exist.

In your example, could the current token be on `+`, causing the second `numericalExpression` to be evaluated in no-predicates mode?

**Comment by mike-lischke** [comment]
Well, in my case the predicate isn't ignored. It's just evaluated too early. What I'm after here is that I don't see a `FailedPredicateException` where I would expect it. That part worked differently in ANTLR3, where I could use this exception to construct an error message which included knowledge about the predicate that failed (e.g. to tell the user that his input would work under different conditions). I don't see how to implement that in ANTLR4, since I cannot get the exception to throw (where it did before), which is a significant regression.

**Comment by sharwell** [comment]
In ANTLR 4, a `FailedPredicateException` means the grammar was constructed in such a way that the ALL(*) algorithm itself failed to produce a correct prediction. In other words, its use is more as an indication that the *grammar* is in error (or outside the capabilities) as opposed to the *input* in error.

If you want to gate some alternative after prediction is made, you can use an action which throws an exception instead of using a predicate.

**Comment by mike-lischke** [comment]
Hmm, interesting idea. I'll give actions with exceptions a try, thanks

**Comment by sharwell** [comment]
:memo: In case you are wondering, most of the reasoning for the major change in predicate behavior was fallout from two things:

1. The complete elimination of backtracking in ANTLR 4
2. The effort to eliminate invalid state during predicate evaluation caused by hoisting predicates out of context in ANTLR 3
