### ISSUE TITLE
Add a more understandable message than "Serialized ATN data element .... element ... out of range 0..65535"

### ISSUE THREAD

**Issue by jbarotin** [antlr/antlr4#1863]
Hi,

I tried to build a big grammar file with antlr4. I've  got the following message when I execute the ANTLR  code that generate java source : 
```
Exception in thread "main" java.lang.UnsupportedOperationException: Serialized ATN data element ```
101246 element 11 out of range 0..65535
        at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:361)
        at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
        at org.antlr.v4.codegen.model.SerializedATN.<init>(SerializedATN.java:22)
        at org.antlr.v4.codegen.model.Recognizer.<init>(Recognizer.java:64)
        at org.antlr.v4.codegen.model.Lexer.<init>(Lexer.java:27)
        at org.antlr.v4.codegen.OutputModelController.lexer(OutputModelController.java:151)
        at org.antlr.v4.codegen.OutputModelController.buildLexerOutputModel(OutputModelController.java:104)
        at org.antlr.v4.codegen.CodeGenerator.generateLexer(CodeGenerator.java:119)
        at org.antlr.v4.codegen.CodeGenPipeline.process(CodeGenPipeline.java:54)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:404)
        at org.antlr.v4.Tool.process(Tool.java:354)
        at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:321)
        at org.antlr.v4.Tool.main(Tool.java:168)
```

From what I understand, my grammar file is too long.

Is that possible to get a message to explain that the limitation of the library is reached ?

For your test, here it is my grammar file ( a bit cryptic cause I anonymize it) :
https://gist.github.com/jbarotin/7f7caf419b9038c2a548969265788392

**Comment by ericvergnaud** [comment]
Hi,
By the looks of it, you are confusing structure and content. No structure or language grammar has thousands of keywords.  Instead they have patterns to consume all those words or sentences generically. You should look at determining those patterns. Antlr will produce an AST which you can then traverse to interpret the exact words.
Eric

Envoyé de mon iPhone

**Comment by jbarotin** [comment]
Thanks for your answer, you are exactly describing the way I'm implementing my grammar right now. 

But I loose time to understand why it's not working. I think that improve the message (by intercepting the exception) will save time to crazy that want to build a big grammar.

**Comment by ericvergnaud** [comment]
To save time, maybe you should start by reading the book?
Hard to say with obfuscated keywords, but I bet most of your rules (such as 'end_event_value') could be coded using an ID or something similar instead of thousands of possible values.

**Comment by jbarotin** [comment]
Yes exactly, it's not a big deal 'end_event_value' must be equal to a strict list of value. I'll validate this dynamically thought the AST.

Right now, I have not enough time to read the book, I'm just building a small tools to automatize validation of expert rules... but I have already used the boost spirit library in the past.

**Comment by jbarotin** [comment]
Anyway, it was just a suggestion, if you think it's a good idea but you've no time to do that, I can try to submit a pull request. Otherwise, you can close the issue.

**Comment by ericvergnaud** [comment]
Yes please submit a PR

Envoyé de mon iPhone

**Comment by KvanTTT** [comment]
@ericvergnaud the question is not about bad-written grammar but about the informative error message. It's possible to get such error thus we have to handle it properly and show a correct message.

**Comment by KvanTTT** [comment]
I understand how it could be fixed. Only one value exceeds the range `0..65535`, it's the number of ATN states [ATNSerializer.java#L85](https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java#L85) (it has 11 index in data). It's possible to save the length in two words that allow up to 2^32 ATN states. This change may be back-compatible if use an algorithm with varying bytes count (if size in 0..32768 range then use 1 byte, overwise use 2 bytes for size). But actually, back-compatibility does not matter in this case because runtimes have [version checks](https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/RuntimeMetaData.java#L144-L167) and generated files are not compatible with the tool of another version.

I think we should increase the size limit because there are similar user bug reports over the repository: https://github.com/antlr/antlr4/issues/840, https://github.com/antlr/antlr4/issues/2732, https://github.com/antlr/antlr4/issues/3338. And 65535 is really not a big limit, some grammars require more states.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/3591
