### ISSUE TITLE
Unhelpful error message 

### ISSUE THREAD

**Issue by objmagic** [antlr/antlr4#2179]
Issue reproducible with  

**ANTLR version: 4.5**
**Code generation target: Java**

---

With the following grammar and [start rule name](https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/gui/TestRig.java#L59) being `exprEof`,

```
grammar G;

exprEof
    : expr EOF
    ;

expr
    : Uident
    | expr '(' Uident ')'
    ;

Uident
    : [A-Z][a-z]*
    ;

WS
    : [ \n\t]+ -> skip
    ;
```

expression `Foo(A B)` gives me meaningful error message as expected:

```
line 1:6 extraneous input 'B' expecting ')'
(exprEof (expr (expr Foo) ( A B )) <EOF>)
```

However, without changing start rule name, if I add **a new rule `expr2`, which will not be used at all**:
```
grammar G;

exprEof
    : expr EOF
    ;

expr
    : Uident
    | expr '(' Uident ')'
    ;

expr2
    : expr '(' Uident ')'
    ;

Uident
    : [A-Z][a-z]*
    ;

WS
    : [ \n\t]+ -> skip
    ;
```
Error message then becomes the following, which gives no clue at all:
```
line 1:3 mismatched input '(' expecting <EOF>
(exprEof (expr Foo) ( A B ))
```

**Comment by objmagic** [comment]
Ping. I would appreciate any update.

**Comment by ericvergnaud** [comment]
Hi,

the place for support is the google discussion group.

Eric

**Comment by parrt** [comment]
Hi.  Have you tried using the full LL mode? That is the issue here. Even though that rule is not directly called, the expression rule is called from that and so is a potential return point in SLL mode

**Comment by KvanTTT** [comment]
The issue is reproducible both in `SLL` and in `LL` mode.

**Comment by parrt** [comment]
interesting.  I think the issue here is that the grammar

```
expr
    : Uident
    | expr '(' Uident ')'
    ;
```

indicates that it can match just an identifier or a function call. because it did not get the call it's fell back on the identifier and then could not match a future rule.  Not sure what to suggest but this is not a bug in the parsing strategy. I suggest that you try something like

```
expr
    : expr '(' Uident ')'
    | Uident
    ;
```

 to see if that matters or do it old school

```
expr
    : Uident ( '(' Uident ')' )?
    ;
```

**Comment by KvanTTT** [comment]
But why unrelated rule (that is not used anywhere) affects the parsing strategy and error messages? It looks weird and counterintuitive. I don't think the issue should be closed.

**Comment by parrt** [comment]
I don't think it's related to parsing. I think error messages are created using a global follow, I think in some cases which pulls in this other rule.  I'm closing because I'm not gonna spend any time thinking about any change to the parsing strategy so it would only be for error messages computation.  Even in that case I would be unlikely to approve a change that could possibly screwup error handling messages for other scenarios.
