### ISSUE TITLE
Generated code (for C#) does not compile...

### ISSUE THREAD

**Issue by kepeter** [antlr/antlr4#2289]
Hello,

I run these commands (following the instructions here: [https://github.com/antlr/antlr4/tree/master/runtime/CSharp])
`java -jar antlr-4.7.1-complete.jar -no-listener -visitor -Dlanguage=CSharp JavaScriptLexer.g4`
`java -jar antlr-4.7.1-complete.jar -no-listener -visitor -Dlanguage=CSharp JavaScriptParser.g4`

I got 4 files (attached) that not even compile... (Antlr4.Runtime.Standard  version 4.7.1.1 installed via NuGet)

The grammar files are from here: [https://github.com/antlr/grammars-v4/tree/master/javascript]

[ConsoleApplication4.zip](https://github.com/antlr/antlr4/files/2004929/ConsoleApplication4.zip)

**Comment by ericvergnaud** [comment]
Maybe you are missing the necessary C# files from the CSharpSharwell folder?

**Comment by sharwell** [comment]
> Maybe you are missing the necessary C# files from the **CSharpSharwell** folder?

:memo: I have no idea what **this** is referring to.

**Comment by ericvergnaud** [comment]
Hi,

to this:
https://github.com/antlr/grammars-v4/tree/master/javascript/CSharpSharwell <https://github.com/antlr/grammars-v4/tree/master/javascript/CSharpSharwell>

**Comment by kepeter** [comment]
@ericvergnaud 
Yes I tried those files... The problem that those are depend on an other project (https://github.com/PositiveTechnologies/PT.PM), that not only huge, but also fails to compile (a whole empty folder instead of an expected project)...
In any case I was able to create files for ECMAScript (only two fixes), and that seems to be good for me...

By the way, where can I talk about those fixes? It may be appropriate to add them to the code-base...

**Comment by KvanTTT** [comment]
Just replace `using static PT.PM.JavaScriptParseTreeUst.Parser.JavaScriptParser;` with your parser class.

**Comment by ericvergnaud** [comment]
On the google discussion group 

Envoyé de mon iPhone

**Comment by kepeter** [comment]
@KvanTTT 
No. As I read antlr, the point is that I have not to writer my parser... And how is that that only JavaScript needs a base-parser/lexer that depends on an external library, but C++, C#, Java, PHP, JSON all goes well without?

**Comment by KvanTTT** [comment]
Ar current time all JavaScript and EcmaScript grammars are target-specific (C#, Java, etc.).

**Comment by xied75** [comment]
@kepeter the js grammars at the root (i.e. two g4 files at https://github.com/antlr/grammars-v4/tree/master/javascript), although looks "neutral", but the lexer declared a base class JavaScriptBaseLexer, which for Java target, you goto /Java for two more files, and for cs target, you goto /CSharpSharwell for two cs files. The problem is, according to the surface meaning of this paragraph:

> For C# runtime by Sam Harwell it described by CSharpSharwell/JavaScriptBaseParser.cs

This simply means, the runtime is Sam's flavour, not the Antlr4 official "Standard" flavour. Believe me I have no idea why this is the case. So you would need to run Sam's runtime to get the code compile.

@ericvergnaud @KvanTTT I haven't been looking at antlr4 on the csharp front for quite a while, for some reason lots of grammars were converted into Java specific, even the CSharp grammar itself, e.g. (this file here https://github.com/antlr/grammars-v4/blob/master/csharp/CSharpLexer.g4 is purely for Java target). Why is that? What is the purpose to switch CS into Java?

**Comment by ericvergnaud** [comment]
Those grammars were not 'converted into Java' or 'switched', they were originally written for Java.
Since the reference implementation is Java, it is not surprising and the purpose I guess was to test the tool and runtime against a number of mainstream languages grammars.

**Comment by xied75** [comment]
@ericvergnaud At least for CSharp, those g4 files were targeting CSharp at previous versions.

**Comment by KvanTTT** [comment]
@parrt I think the issue can be closed, it doesn't relate to ANTLR core.
