### ISSUE TITLE
CharSupport.getStringFromGrammarStringLiteral() doesn't handle escaped double quotes anymore

### ISSUE THREAD

**Issue by stephenir** [antlr/antlr4#2290]
This is the expected behaviour, and this worked in v4.6. In v4.7 it no longer works -

Assert.assertEquals("It's \"game\" time.", CharSupport.getStringFromGrammarStringLiteral("\"It's \\\"game\\\" time.\""));

It was broken by this commit -

https://github.com/antlr/antlr4/commit/c5f9d5e2a11b65ff8f9038723dbbe22fca3619f3#diff-4b8c943aa906db259eac227fccfcaf39

Perhaps this is not a bug and is intentional, I don't understand the intent of the commit well enough.

**Comment by KvanTTT** [comment]
`getStringFromGrammarStringLiteral` is actual only for ANTLR string literals. ANTLR uses only single quotes `'` for string literals but not double quotes `"`, see [lexicon.md#literals](https://github.com/antlr/antlr4/blob/master/doc/lexicon.md#literals). That's why double quotes should not be escaped.

@parrt I think it can be closed.
