### ISSUE TITLE
aggregateResult should only return null if both arguments are null.

### ISSUE THREAD

**Issue by DaOnlyOwner** [antlr/antlr4#2303]
Hello guys, 

The function "aggregateResult" in "AbstractParseTreeVisitor" should not return "nextResult" by default because that's not what one would expect IMO. For example assume that "nextResult" is null, but "aggregate" is user specified (not null), then the expected result is not to return "nextResult" but "aggregate". I suggest the following change:

```
protected T aggregateResult(T aggregate, T nextResult) {
	if (nextResult != null) return nextResult;  
        else if (aggregate != null) return aggregate;
        else return null;
}
```
Does that make sense?

Greetings

**Comment by sharwell** [comment]
I'm concerned about this being an unnecessary breaking change for an API included in several stable releases right now. `aggregateResult` returns the *last* result by default, and users are expected to override the behavior if they need to handle it in a different way.

**Comment by sharwell** [comment]
It turns out the current behavior is explicitly documented in the API contract for the purpose of allowing code to rely on this behavior over time:

https://github.com/antlr/antlr4/blob/61acb35f0cb9ec0743cb6edba6973c33bd56cc30/runtime/Java/src/org/antlr/v4/runtime/tree/AbstractParseTreeVisitor.java#L96-L98

**Comment by DaOnlyOwner** [comment]
I agree that this would introduce a breaking change, it was just a suggestion for following releases.
Thanks anyways,
Greetings

**Comment by sharwell** [comment]
@DaOnlyOwner It's not a bad suggestion. I was back-and-forth on the behavior for this method since it's obvious that the current implementation only makes sense in a subset of applications. It's been a while now, but I believe I finally settled on the current approach since it's easy to explain and easy to map to other target languages, including ones where `null` isn't always a valid value for type `T`. 😄
