### ISSUE TITLE
I would like to add support for TypeScript

### ISSUE THREAD

**Issue by wickedev** [antlr/antlr4#2592]
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

I think that supporting the Typescript in the official repository is more beneficial in terms of IDE support than using antlr4ts. So I think there are two ways to do this:

- First option, generate a d.ts (Declaration File) using needsHeader for an existing JavaScriptTarget
- Second option, create a separate TypescriptTarget

I would like to hear what you prefer.

**Comment by ericvergnaud** [comment]
First option is much easier to maintain

**Comment by wickedev** [comment]
I'm little bit confusing. TypeScript compiler treats JS as like a TypeScript when there are d.ts files of same name. is your intention was add both options(generate js + d.ts files or only generate a .ts files) to JavascriptTarget?

**Comment by ericvergnaud** [comment]
I have no intention, but my preferred option would be to generate .ts files only. 
However, I am under the impression that this will not suffice to have a clean working Typescript target, because utilities such as antlr4.InputStream need to be called in order to get something done.
For these utilities, and the ones used internally by the generated parser and lexer, am I wrong in believing the Typescript target will need to expose d.ts files for the Javascript runtime?

**Comment by GordonSmith** [comment]
You can generally get away without having to declare d.ts files for the internally used utilities (unless they end up getting re-exported).

Given the generated .ts files will typically end up being "my source" and not an imported library you may need to set
```
   "skipLibCheck": true,
```
in your tsconfig.js (which basically disables the need to have d.ts files for imported JS libs.)

IMO the "big win" would be having typed contexts for visitors, the rest I could live without.
