### ISSUE TITLE
Stack overflow using a grammar that has an extraneous | in a token definition

### ISSUE THREAD

**Issue by omry** [antlr/antlr4#2860]
Minimal grammar:
```                                                   
grammar test;                                                                            
                                                                                        
TILDE: '~';                                                                              
                                                                                         
fragment                                                                                 
QSTRING: (TILDE|)+;                                                                      
                                                                                         
QUOTED_VALUE:  '\'' QSTRING? '\'' ;                                                      
                                                                                     
single_value: QUOTED_VALUE ;                                                             
```

Building and running results in a stack overflow.
I saw this first on the Python runtime and then the same issue on the Java runtime (using grun).
This is using **antlr-4.8-complete.jar**.
```
antlr4 *.g4 && javac *.java && echo -n "'~'" |  grun test single_value -tokens
Exception in thread "main" java.lang.StackOverflowError                                  
        at org.antlr.v4.runtime.misc.Array2DHashSet.getOrAdd(Array2DHashSet.java:59)     
        at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:146)              
        at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:122)              
        at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:446)
        at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:455)
        at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:455)
```

**Comment by KvanTTT** [comment]
Your rule is quite strange because of the empty alternative. Try to just remove it:

```g4
fragment
QSTRING: TILDE+;
```

But you are right in one thing: stack overflow exception should not be thrown here anyway.

**Comment by omry** [comment]
After spending the time narrowing it down the workaround is indeed obvious.

**Comment by omry** [comment]
If an empty alternative is illegal, it should be rejected by the tool.
If it's legal, it should work and do something well defined.

there is no middle ground.

**Comment by WalterCouto** [comment]
Didn't the compiler issue a warning about the use of an empty alternative? There are valid cases out there that an empty alternative is used, so the warning should be good enough to detect rules that need a further review.
if I rewrite the rule to use the alternative syntax for that empty option, it would look like:

QSTRING: TILDE?+;

Which is already a little weird, maybe looks a little less weird in the  usual form, that make a bit more sense:

QSTRING: TILDE+?;

Which really means:

QSTRING: TILDE*;

Though all of them can be considered questionable as the rule can match empty, I bet the simplified rule above would not have the issue. This rule is still a bit weird in its form since the only use of the QSTRING rule is itself optional with "QSTRING?", so you are optional matching something that is already optional.  The final form of that rule should clearly be:

QSTRING: TILDE+;

Since the optional part is handled by the other rule using QSTRING.  In this form, I bet again that you will not see the issue. In this case, I think as long as you got the warning, that should have been enough to trigger a review of that rule as shown above that would have led to you avoiding the issue.

**Comment by omry** [comment]
no warrnings:
```shell
omry@Coronadev:~/tmp/1$ cat test.g4 
grammar test;
TILDE: '~';
fragment
QSTRING: (TILDE|)+;
QUOTED_VALUE:  '\'' QSTRING? '\'' ;
single_value: QUOTED_VALUE ; 

omry@Coronadev:~/tmp/1$ java -jar ~/bin/antlr-4.8-complete.jar test.g4 
omry@Coronadev:~/tmp/1$ 
```

**Comment by omry** [comment]
to clarify:
I did not intent to match the empty alternative.
it was a user error. I had to spend some time narrowing down my grammar to near nothing to find the error.

**Comment by SimonSntPeter** [comment]
I think I hit the same (can't be sure as I changed the grammar after, and now I can't reproduce but same symptoms, see <https://groups.google.com/forum/#!searchin/antlr-discussion/domino/antlr-discussion/CDt7lPLyMhU/thJ1-XZAAQAJ>).

In fact, see that thread for a tiny utility that may help pick these up.

**Comment by KvanTTT** [comment]
Minimal reproducible example:

```g4
lexer grammar T;
TOKEN: ('x'|)+?;
```

With any input.

**Comment by KvanTTT** [comment]
I suggest restricting matching empty strings not only for ordinary tokens but fragments too. I.e. changing the warning `EPSILON_TOKEN`  (`non-fragment lexer rule FRAGMENT can match the empty string` -> `lexer rule FRAGMENT can match the empty string`).

Also, I suggest converting this warning into an error since it may cause stack overflow on runtime that's much more critical.
