### ISSUE TITLE
Grammar factorization causes context unusual behavior

### ISSUE THREAD

**Issue by NicoLaval** [antlr/antlr4#2862]
Grammar file:
```

expr:
    left=expr op=(PLUS|MINUS|CONCAT) right=expr                           # arithmeticExprOrConcat
    | left=expr op=comparisonOperand  right=expr                            # comparisonExpr

comparisonOperand:
    MT
    | ME
    | LE
    | LT
    | EQ
    | NEQ
;
```
Accessing to context type to switch/case on operands into `visitArithmeticExprOrConcat` is basically `ctx.op.getType()`.

Contrariwise, it's not so obvious in `visitComparisonExpr`.
Actually, a tricky way to obtain it is `Token type = ((TerminalNode) ctx.op.getChild(0)).getSymbol();`

The fact that operands are grouped into a dedicated declaration instead of expression body seems to dupe antlr.

**Comment by kaby76** [comment]
This is the correct behavior. Every "ctx" passed to a visitor method is an internal node in the parse tree, i.e., it is subclassed from ParserRuleContext. Internal nodes can span multiple lexer tokens, so getType() isn't available--an internal tree node does not have one token type. In the first "op" case, the expression "op=(PLUS|MINUS|CONCAT)" generates on ExprContext a field "public Token op;". "op" here denotes a Token because PLUS, MINUS, CONCAT are in upper case symbols, therefore all lexer tokens. That's why ctx.op.getType() compiles. However, in the second "op" case, the expression "op=comparisonOperand" generates on ExprContext a field "public ComparisonOperandContext op;". This "op" is for a ComparisonOperandContext, which is a ParserRuleContext, which is an internal node in the tree. In other words, there is an extra node in the parse tree corresponding to the symbol comparisonOperand. That's why you have to first do a getChild(0). You should probably review what the parse tree looks like by printing it out.

**Comment by NicoLaval** [comment]
Fine, thanks for your detailed explanation
