### ISSUE TITLE
[Cpp] Can't use antlr and cstdio together because of undef EOF

### ISSUE THREAD

**Issue by cangfengzhs** [antlr/antlr4#2914]
I use another lib(brpc)  which use macro EOF, but anltr(4.8) undef it in antlr-common.h. 
In order to use them at the same time, I need to strictly control the order of the include, otherwise the compilation will fail.
How to solve this problem?

**Comment by Marti2203** [comment]
Hi, Copy the definition at before including and put it back after including the antlr-common.h?

**Comment by cangfengzhs** [comment]
I think EOF should be replaced by _EOF and delete undef? After all, EOF is defined by the standard library. Although this problem can be avoided to some extent by modifying the include order of header file, it will be adjusted when using cpplent to format code automatically.

**Comment by shahms** [comment]
EOF is a reserved identifier (by virtue of being defined by the C standard library). User programs cannot redefine it and Antlr should not generate code which does.  And it certainly shouldn't be undefining it in a common header.

**Comment by parrt** [comment]
I'm fine with such a change if EOF reserved is C++ (not just C). @mike-lischke @jcking have an opinion?

**Comment by parrt** [comment]
How much will it break if we added EOF to the keywords list so that is generated `EOF_`?

**Comment by parrt** [comment]
@jcking points out:

Basically anywhere EOF is mentioned outside comments, you have to add this before:

```
#pragma push_macro("EOF")
#undef EOF
```

And this after:

```
#pragma pop_macro("EOF")
```

And then remove the `#undef EOF` in the header.

**Comment by shahms** [comment]
It's reserved in C++ as well:

https://eel.is/c++draft/macro.names
https://eel.is/c++draft/cstdio.syn

**Comment by mike-lischke** [comment]
Tbh. I don't see a need to change that. It has been this way since 2016 and the vast majority of the C++ ANTLR4 user have not had any problem with it. We cannot please everyone.

**Comment by shahms** [comment]
The issue here, as is often the case with undefined behavior, is fragility.  UB can happen-to-work for quite a while until it doesn't and then you're hit with a variety of problems. At least here, it's a compilation failure rather than silent corruption at runtime, but it can happen for a number of reasons including that a transitive dependency changed the order of `#include` files.  When this happens, there isn't much recourse for users short of omitting mention of `EOF` from their grammar (against the "best practices" documentation), not updating a dependency (potentially leaving them open to security vulnerabilities) or hackily adjusting the generated code with `sed` or equivalent.

While it's true that you "cannot please everyone" it's also the case that the current situation is a ticking time bomb for your currently-pleased users.

**Comment by parrt** [comment]
At least with one example we have found that removing a reference to `EOF` from the grammar (start rule) allows the generated code to build even if you include `cstdio`. To get the same functionality, you can add a quick check after the parse to ensure that the token stream index is the length of the token stream. This is a hack but I'm not sure how to overcome the collision with EOF macro. Just leaving this note here for other travelers.

For the next major release I can see adding EOF to the reserved keywords list and having it convert to `EOF_` Or, we can try the `#undef` trick.

Thanks everyone!

**Comment by mike-lischke** [comment]
@shahms I don't think this issue is a potential time bomb. It's not like it just happened to work. Quite the opposite: only very few user used the EOF C macro and knew how to work around the #undef in the ANTLR4 C++ runtime. Most C++ users didn't even see a problem, because it is related to a very narrow area (using C stuff in a C++ application).

@parrt A simpler solution is to change to include order of header files. That usually works well already. But @shahms is right here, it can happen that you cannot change that order. The "correct" solution would be that ANTLR4 doesn't use `EOF` as it is a special word in C/C++ (not reserved, but still).

**Comment by parrt** [comment]
Ok, I've played around with this problem and thought about it. I just can't see breaking all previous ANTLR code that references EOF buy renaming it out `EOF_`.  Yes, we should have avoided EOF at the beginning but I can't change reality.

The "solution" is to avoid referencing EOF in your actual grammar or add `#undef EOF` in a section to get it into the generate a code in the right spot. Something like this:

```
@parser::members {
#undef EOF
}
```

I also can't change the fact that C++ uses include files from the 1960s and that order matters.  Oh and that it still has a preprocessor with macros that can completely change the syntax.  C++ is over 40 years old now and still accreting features aggressively. Let's see if we can make it to 50! <snark>

**Comment by parrt** [comment]
Happy to reopen this if we get a better solution!

**Comment by JoD** [comment]
Hey all

Just bumped into this issue when trying to use ANTLR to parse to Boost multiprecision integers:
```
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /home/jod/workspace/exact-dev/src/manyworlds/ManyWorlds.hpp:23,
                 from /home/jod/workspace/exact-dev/src/manyworlds/Expression.hpp:71,
                 from /home/jod/workspace/exact-dev/src/manyworlds/parser/Parser.cpp:22:
/usr/include/boost/multiprecision/number.hpp: In function ‘std::istream& boost::operator>>(std::istream&, boost::rational<boost::multiprecision::number<Backend, ExpressionTemplates> >&)’:
/usr/include/boost/multiprecision/number.hpp:2137:12: error: ‘EOF’ was not declared in this scope
 2137 |    while ((EOF != (c = static_cast<char>(is.peek()))) && (c == 'x' || c == 'X' || c == '-' || c == '+' || (c >= '0' && c <= '9') || (have_hex && (c >= 'a' && c <= 'f')) || (have_hex && (c >= 'A' && c <= 'F'))))
      |            ^~~
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /home/jod/workspace/exact-dev/src/manyworlds/ManyWorlds.hpp:23,
                 from /home/jod/workspace/exact-dev/src/manyworlds/Expression.hpp:71,
                 from /home/jod/workspace/exact-dev/src/manyworlds/parser/Parser.cpp:22:
/usr/include/boost/multiprecision/number.hpp:33:1: note: ‘EOF’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
   32 | #include <cctype>  // isspace
  +++ |+#include <cstdio>
   33 | #ifndef BOOST_NO_CXX17_HDR_STRING_VIEW
```
The grammar did not mention any EOF, so to me the proposed workaround did not work. 

For now, I try to ensure that the Antlr includes are processed *after* the multiprecision includes, which is quite a pain, as the autoformatter likes to reorder includes, and as I do not have a good idea how exactly the compiler orders the includes in C++.

So to me, this is actually an issue that makes me think about not using Antlr. Are there any other workarounds?

**Comment by cangfengzhs** [comment]
This is also a key reason why I don't consider using Antlr

**Comment by parrt** [comment]
@JoD interesting that EOF was automatically added even if it's not in the grammar... Can you post the grammar? Often people get around things by the order of includes.

@cangfengzhs I totally understand. We are in a difficult situation because they see plus plus model was created long before we started thinking carefully about the cross platform reserved words collision problem. There is so much C++ code out there that I hate to break all of that to tweak the antlr runtime for EOF.

**Comment by raffopazzo** [comment]
I just hit this problem just by including `boost::iostreams` on a brand new project. Whilst I can see that you don't want to break existing code, this is also preventing writing new one. What about guarding your `#undef` with some `#ifdef ANTLR4CPP_LEGACY_EOF` and old code that just `-D` that in their build? or maybe some `options { EOF=EOF_; }` in the grammar so that new code can "rename away from EOF"?

**Comment by wangtao9** [comment]
I also encountered the same problem. In [this modification](https://github.com/wangtao9/antlr4/commit/63b1ba05f498b5cd0bc4c7f6f20df41f92c5dad7), I tried to remove `#undef EOF` from the Cpp-runtime, but I don't know how to modify the demo's g4 file https://github.com/antlr/antlr4/blob/dev/runtime/Cpp/demo/TParser.g4  to generate a correct parser.
The error message is as follows:
```
Consolidate compiler generated dependencies of target antlr4_shared
[ 47%] Built target antlr4_shared
Consolidate compiler generated dependencies of target antlr4_static
[ 93%] Built target antlr4_static
[ 94%] Built target gtest
[ 95%] Built target gtest_main
[ 96%] Built target antlr4_tests
[ 96%] Built target gmock
[ 97%] Built target gmock_main
[ 97%] Built target GenerateParser
Consolidate compiler generated dependencies of target antlr4-demo
[ 98%] Building CXX object demo/CMakeFiles/antlr4-demo.dir/Linux/main.cpp.o
In file included from /usr/include/c++/11/cstdio:42,
                 from /usr/include/c++/11/ext/string_conversions.h:43,
                 from /usr/include/c++/11/bits/basic_string.h:6608,
                 from /usr/include/c++/11/string:55,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from /home/wt/antlr4/runtime/Cpp/demo/Linux/main.cpp:13:
/home/wt/antlr4/runtime/Cpp/demo/generated/TParser.h:82:33: error: expected unqualified-id before ‘-’ token
   82 |     antlr4::tree::TerminalNode *EOF();
      |                                 ^~~
/home/wt/antlr4/runtime/Cpp/demo/generated/TParser.h:82:33: error: expected ‘)’ before ‘-’ token
   82 |     antlr4::tree::TerminalNode *EOF();
      |                                 ^~~
```

**Comment by punk-floyd** [comment]
@parrt You mentioned that you might reopen this if you had a better solution.

The undefining of EOF also breaks all C++20 standard formatting, both std::format (GCC) and fmt::format.

Omitting EOF in the grammar is not a fix because antlr4-common.h unconditionally undefines it. Having to play games with include file order is extremely brittle and a looming footgun for some hapless soul in the future.

I believe I have a solution that will not break existing source code. It plays games with macros, which I loathe, but we're already firmly in that territory. Here's the general idea. My names are just suggestions.
```cpp
// Define Cpp runtime API in terms of EoF (for example) instead of EOF
enum class Token { EoF };   // etc...

// In antlr4-common.h
#ifndef ANTLR_DO_NOT_CLOBBER_C_EOF
# ifdef EOF		// Undefine as you've been doing
#  undef EOF
# endif
// Rename EOF to EoF so existing code continues to build okay. This
// continues to clobber EOF, but we're doing that anyway so it's clearly not
// a problem for existing codebases.
# define EOF EoF
#endif
```

Existing code will continue to compile as before, assuming no one uses `EoF`. New code can just define `ANTLR_DO_NOT_CLOBBER_C_EOF` via the build system and not have a clobbered EOF symbol for their code.

While I have your ear, this is a great library. Thank you for creating it.

**Comment by parrt** [comment]
Seems clever but maybe some of the c++ folks should comment?

**Comment by raffopazzo** [comment]
@punk-floyd @parrt 
I made a similar suggestion previously on this thread, admittedly not as well elaborated.
https://github.com/antlr/antlr4/issues/2914#issuecomment-1620796853

As a c++ user I would have been happy to add the definition suggested by punk to my build system

**Comment by parrt** [comment]
@mike-lischke Could you give a ruling on this?

**Comment by mike-lischke** [comment]
@punk-floyd What if you put EOF in the antlr namespace? That will break existing code, I know, but that's a one-time break (do a new major version release and document properly to make users are aware there's a breaking change).

**Comment by punk-floyd** [comment]
@mike-lischke Not sure I follow regarding the namespace.

For anyone that includes stdio.h (directly or transitively), the token 'EOF' is just a synonym for "`(-1)`":
```cpp
// Code written like this...
static constexpr size_t EOF = std::numeric_limits<size_t>::max();
// ...is compiled like this. This is clearly bad code.
static constexpr size_t (-1) = std::numeric_limits<size_t>::max();

// Trying to wrap in a namespace won't help here
namespace antlr { inline constxpr auto EOF = std::numeric_limits<size_t>::max(); }
// Compiles to:
namespace antlr { inline constxpr auto (-1) = std::numeric_limits<size_t>::max(); }
```

As you've discovered, if you want to use EOF as a symbol name, the only option you have is to nuke the macro with an #undef. This allows antlr code to use EOF as a symbol name, but breaks the code that expects EOF to be -1.

Just in case my proposal wasn't clear, let me be a more specific. In the Cpp runtime code, replace standalone uses of 'EOF' with 'EoF'. For example:
```cpp
// In runtime/Cpp/runtime/src/IntStream.h
static constexpr size_t EoF = std::numeric_limits<size_t>::max();
// In runtime/Cpp/runtime/src/Token.h
static constexpr size_t EoF = IntStream::EoF;
// ... and so on

// Symbol names like isMatchedEOF or string literals "EOF" are unaffected by the macro.
```

Doing the above eliminates the problem of conflicting with the EOF macro. However, it breaks all existing code using the Cpp runtime. That's not cool. To fix this, we go back to the nuclear #undef option but with a twist and an escape hatch for those that want to opt in and "keep" to the newer 'EoF' API.

In `antlr4/runtime/Cpp/runtime/src/antlr4-common.h`
```cpp
// Original code
#ifdef EOF
#undef EOF
#endif

// Proposed code
#ifndef ANTLR_DO_NOT_CLOBBER_C_EOF
# ifdef EOF		// Undefine as you've been doing
#  undef EOF
# endif
# define EOF EoF
#endif
```

With the above changes, existing code still works:
```cpp
// Existing code written like this...
if (_input->LA(1) == EOF) { ... }
// ...is compiled like this:
if (_input->LA(1) == EoF) { ... }
```

New projects can opt-in with a `#define ANTLR_DO_NOT_CLOBBER_C_EOF` in their project settings and use the EoF symbol from the get go (e.g., `MyLexer::EoF`). Or, if an API break is on the table, you can forgo the whole ANTLR_DO_NOT_CLOBBER_C_EOF thing, leave EOF alone, and just document that folks need to update their code to use EoF instead of EOF. That's kind of heavy handed, but provides a clean break.

At any rate, I think the idea is sound but I know nothing about the internals of the antlr codebase. Otherwise, I would do a pull request myself. There are three entities in the mix and I don't know how they all fit together: the antlr Java backend, the Cpp runtime, and the generated code.

**Comment by mike-lischke** [comment]
I didn't expect that in code like this:

```C++
namespace antlr { inline constxpr auto EOF = std::numeric_limits<size_t>::max(); }
```

the `EOF` symbol would be replaced by (-1). But yes, that's how macro replacement in C/C++ works. However, you could undef `EOF` if it exists, add the namespace EOF and then (if it was defined) define the macro again. Would that work? I have no C++ environment here to test.
