### ISSUE TITLE
Travis continuous integration is no longer an option; need new location

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#3029]
Howdy! @ericvergnaud  has graciously agreed to lead a discussion to figure out how to get continuous integration up and running again. The good news is that we at least have appveyor still working. Further, I just figured out how to use github actions... fairly straightforward actually. Here's an example where I run a bunch of Python unit tests after installing a bunch of libraries:

https://github.com/parrt/tensor-sensor/blob/master/.github/workflows/test.yml

And you get the results that look like this page:

https://github.com/parrt/tensor-sensor/actions/runs/467542701

**Comment by niw** [comment]
Hi! I recently posted a few pull requests (such as #3025) and Appveyor task failed, seems like due to missing php. Is it related to the Travis retirement? This is not directly related to this topic however, if Appveyor is the only current CI option right now, probably I think it would be better to address that issue. (Or... probably I am wrong about why Appveyor failed...?)

**Comment by parrt** [comment]
AppVeyor should be fixed how @niw. For example https://ci.appveyor.com/project/parrt/antlr4-l7imv

**Comment by parrt** [comment]
Ok, closing this. let's try using https://github.com/antlr/antlr4/discussions/3031 that i just turned on.

**Comment by niw** [comment]
@parrt Oops, sorry, I should've open new issue than asking it this thread... Thank you for fixing AppVeyor!!
