### ISSUE TITLE
ambiguous import:

### ISSUE THREAD

**Issue by xiazemin** [antlr/antlr4#3188]
% go get -u github.com/xiazemin/sqlc/cmd/sqlc@v1.12.0
github.com/xiazemin/sqlc/cmd/sqlc imports
	github.com/xiazemin/sqlc/internal/cmd imports
	github.com/xiazemin/sqlc/internal/compiler imports
	github.com/xiazemin/sqlc/internal/engine/sqlite imports
	github.com/antlr/antlr4/runtime/Go/antlr: ambiguous import: found package github.com/antlr/antlr4/runtime/Go/antlr in multiple modules:
	github.com/antlr/antlr4 v0.0.0-20200209180723-1177c0b58d07 (/Users/xiazemin/go/pkg/mod/github.com/antlr/antlr4@v0.0.0-20200209180723-1177c0b58d07/runtime/Go/antlr)
	github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20210521184019-c5ad59b459ec (/Users/xiazemin/go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210521184019-c5ad59b459ec)

**Comment by Joakker** [comment]
You should update your go.mod so it imports `github.com/antlr/antlr4/runtime/Go/antlr`, as the module is located in that subdirectory instead of the repository root.

**Comment by xiazemin** [comment]
thanks,this works

**Comment by chaseMengdi** [comment]
Hello， do you mean `go get -u github.com/antlr/antlr4/runtime/Go/antlr`

**Comment by tschaub** [comment]
I just ran into the same trying to install an update of a module that depends on this one (`go get -u github.com/kyleconroy/sqlc`).

After the `go get`, `go mod tidy` failed with
```
ambiguous import: found package github.com/antlr/antlr4/runtime/Go/antlr in multiple modules
```

I was able to fix things by doing this:

- remove references to `github.com/antlr/antlr4` in `go.mod`
- run `go mod tidy`

**Comment by bcmills** [comment]
The simple solution here (on the caller side) is to run `go get -d github.com/antlr/antlr4`. That should upgrade you to the latest version of the `antlr4` root module, which contains only the package `github.com/antlr/antlr4/doc/resources`.

(`go mod tidy` will then likely remove that dependency altogether, although it may preserve it if needed to avoid the `ambiguous import` error; see https://github.com/golang/go/issues/47738.)

**Comment by HuangXiaoFengGitHub** [comment]
> 

thanks,it works

**Comment by jimidle** [comment]
The Go module is now at v4. Please see the upgrade instructions in the go target documentation or the v4 pkg.go.dev. 

[Go target docs](https://github.com/antlr/antlr4/blob/master/doc/go-target.md)

Because we released a v4.11.1 tag as well as a 4.11.1 tag, the version will not pick up correctly until the next release, when I hope we will not release a `v` tag and then the go module will work as any other module. It works now, but your go.mod will create the version number as the v4 tag is not valid for go modules.

Hopefully, we can avoid the `v` tag next time @parrt ? But we should have a talk about this - maybe at the next video call.

**Comment by parrt** [comment]
Happy avoid the v tag; only added it before because the Go folks said they needed it. haha!! :)

**Comment by bcmills** [comment]
@jimidle, if an inappropriate tag was applied by accident, consider adding a `retract` directive to that module's `go.mod` file to explicitly retract that tag.

**Comment by jimidle** [comment]
We could do that Bryan, but given that there are other users of the tags, I
feel that least impact is best. In order to do the retract, we would still
have to make a release. So next time we avoid the explicit v tag, (which
would of course actually be the correct tag, except the module is not at
the root of the repo).

The v1.4.11 tag works, but at the moment, the v4.11.1 tag will not except
that go will put the entire source tree (well, mostly) in the local cache
and not just the go module. At next release the actual tag will work. I
have a few more bugs to fix and improvements to add, then perhaps we can
make a ..point release and all the stars will align :)

**Comment by parrt** [comment]
@jimidle can I close this?

**Comment by jimidle** [comment]
> @jimidle can I close this?

Yes Ter - this will resolve with the next release.
