### ISSUE TITLE
[Question] Why is the ATN of the following lexer rules different from the javadoc of ATNState

### ISSUE THREAD

**Issue by chengniansun** [antlr/antlr4#3297]
I have the following toy lexer
```
fragment DIGIT
    : [0-9]
    ;

NaturalNumber
    : DIGIT+
    ;
```

According to the [javadoc of ATNState](https://www.antlr.org/api/Java/org/antlr/v4/runtime/atn/ATNState.html), the ATN of `NaturalNumber` should start with `RuleStartState --> PlusBlockStartState`. 

But In fact, a path in the ATN looks similar to

```
RuleStartState -> BasicState -> SetTransition[0-9] ->RuleStopState -> BlockEndState 
          ^                                                               |
          |                                                               |
  BasicState <----------------------  PlusBlockStartState <- ... <- PlusLoopbackState
```

Could someone advise why the ATN is changed in this way, and is it possible to get a `canonical` ATN as described in the javadoc of `ATNState`?

Thanks in advance.

**Comment by ericvergnaud** [comment]
Please move this to the google discussions group

**Comment by sharwell** [comment]
It seems like it would be better to convert this to a GitHub discussion instead of moving it to a completely different medium.

![image](https://user-images.githubusercontent.com/1408396/136417378-8bd84dff-878c-4fbf-b519-575653ced8f7.png)

![image](https://user-images.githubusercontent.com/1408396/136417294-faf2db7f-faec-4627-a6c4-98c843c2c3dd.png)
