### ISSUE TITLE
antlr.runtime.standard 4.9.3 invalid strong name.

### ISSUE THREAD

**Issue by Barteling** [antlr/antlr4#3360]
Using the latest nuget package 4.9.3 I get invalid strong name exceptions. 
Both the .NETStandard 2.0 and the NET45 version do not seem to be correctly signed. 
4.9.2 seems to be ok, verified with sn.exe

**Comment by ericvergnaud** [comment]
@Barteling I don't think there is any fix in this version for C#, only released for versioning consistency, so you should stick to 4.9.2 until 4.9.4 is available
@parrt I guess this happened because you and I don't follow the same release process (I released 4.9.3, you released 4.9.2) ? When the next release gets prepared, let's make sure we align to avoid this issue.

**Comment by parrt** [comment]
Hi guys. Yep, sorry about that.  I think i grab the artifact from appveyor as that's the limit of my abilities with C# haha.

**Comment by parrt** [comment]
I guess I'll add link to 4.9.4

**Comment by ericvergnaud** [comment]
> Hi guys. Yep, sorry about that. I think i grab the artifact from appveyor as that's the limit of my abilities with C# haha.

4.9.3 was released to Nuget by me so it has nothing to do with AppVeyor

**Comment by KvanTTT** [comment]
It looks like we encountered a similar issue before: https://github.com/antlr/antlr4/issues/2511

**Comment by parrt** [comment]
@ericvergnaud @Barteling @KvanTTT  Can you guys help me figure out how to get the proper artifact and with the right signatures etcetera? I'm going to build and release 4.10 soon.   it seems to be problematic on my mac so I've been downloading the artifact created at circleci.

**Comment by parrt** [comment]
Will close. Updated doc from @ericvergnaud notes to sign properly.
