### ISSUE TITLE
Please restore tag v4.10.1

### ISSUE THREAD

**Issue by kyessenov** [antlr/antlr4#3854]
Downstream projects are failing to build because the tag was removed. See https://github.com/google/cel-cpp/issues/161.

**Comment by jimidle** [comment]
Hmm - were you specifically syncing at the tag? 

We removed v4.10.1 because go mod cannot use that tag and it confuses the bejesus out of it. If you are not using go and modules, then can you instead use the tag 4.10.1 (NB - no `v`), which points at exactly the same hash?

I will try and find a solution if you absolutely have to use the `v` version of the tag. Sorry for the inconvenience.

**Comment by kyessenov** [comment]
I can fix downstream since this is a fairly new release, but that's just me and I have no idea who else got broken. I am not using Go, this is bazel and C++.

**Comment by jimidle** [comment]
So far, we have only your report. If you are happy to change the tag you are using, then please do so and I will keep an eye out for anyone else that may have chosen to use the `v` tags. Hopefully, it will be very few and an easy change. If not, then I will think about a solution for this - but there may not be one.

@parrt  When the tags are done for the next release, we should add a note to the tag to say that the v tags are specifically for Go, so that we can hopefully avoid this. The `v` was chosen for Go to try and avoid clashes with existing tags where the number system would confuse Go.

**Comment by parrt** [comment]
Jim, is there anyway we can get away with restoring the tag? I can’t believe it screws things up

**Comment by jimidle** [comment]
Let’s put it back and see if I can work around it. I think that because it
is not a valid tag for Go, that it will only screw with go if someone asks
for that tag. The new tags will be specified correctly - I think that this
is what was going wrong.

**Comment by jimidle** [comment]
> Jim, is there anyway we can get away with restoring the tag? I can’t believe it screws things up

OK - I think I have cracked it so that all can be happy and we need not change tags in the master branch, which is a bit of a no-no anyway, though I did not realize people outside go were using those `v` tags.

The command sequence is in my comment on #3840

**Comment by jimidle** [comment]
The new tags for use by Go, will no longer be confused with the project's tags. This situation should not arise in the future as the only tags for the project will be absent the `v`. But @parrt will restore these v tags, which will now no longer worry the go mod resolution.

**Comment by saiskee** [comment]
Hi @parrt, thank you for taking on the work of restoring the v tags. When will tag v4.10.1 be restored?

**Comment by parrt** [comment]
Restored!!!

**Comment by jimidle** [comment]
> Hi @parrt, thank you for taking on the work of restoring the v tags. When will tag v4.10.1 be restored?

Apologies - that was my bad thinking.

**Comment by parrt** [comment]
no sweat! all good!
