### ISSUE TITLE
Go runtime panic

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#3929]
@chenquan reported bug here: https://github.com/antlr/antlr4/pull/3834#issuecomment-1279961347

I found this problem in github.com/antlr/antlr4/runtime/Go/antlr v1.4.10. grammar:https://github.com/antlr/grammars-v4/tree/master/sql/mysql/Positive-Technologies

![](https://user-images.githubusercontent.com/20548053/196035594-20e31da3-67e0-422f-967b-ac96245d9a5c.png)

```
panic: interface conversion: antlr.PredictionContext is *antlr.EmptyPredictionContext, not *antlr.ArrayPredictionContext [recovered]
	panic: interface conversion: antlr.PredictionContext is *antlr.EmptyPredictionContext, not *antlr.ArrayPredictionContext [recovered]
	panic: interface conversion: antlr.PredictionContext is *antlr.EmptyPredictionContext, not *antlr.ArrayPredictionContext
```

**Comment by jimidle** [comment]
@parrt @chenquan I cannot reproduce this with the latest runtime code. I have some recollection of fixing this as part of some other code fix, but I cannot be sure. Code should refer to the PredictionContext interface rather than a specific instance. I believe that I fixed this as a byproduct of changing the code that calls mergeArrays, many months ago.

I ran the code above and with the generated visitor it all works as I would expect and there is no panic.

BTW - would you please report bugs with code, rather than a screenshot, so I can be sure I am running the same thing? Cheers :). 

I think that this can be closed.
