### ISSUE TITLE
ANTLR NuGet Runtime Standard: Breaking change

### ISSUE THREAD

**Issue by vasicvuk** [antlr/antlr4#3963]
We have a library that uses `Antlr.Runtime.Standard 4.8.0 and the one that uses 4.11.0. Unforecently those two are crashing because of following error:

```
[2022-11-18 11:09:12Z ERR] Something went wrong: System.TypeInitializationException: The type initializer for 'ExpressionAntlrLexer' threw an exception.
---> System.MissingMethodException: Method not found: 'Antlr4.Runtime.Atn.ATN Antlr4.Runtime.Atn.ATNDeserializer.Deserialize(Char[])'.
--- End of inner exception stack trace ---
```

There should not be a breaking change if only Minor version is increased

**Comment by ericvergnaud** [comment]
Thanks for your opinion but unfortunately we can only guarantee backwards compatibility for patch numbers.Major/minor upgrades require regeneration of the lexers and parsers using the corresponding tool.Envoyé de mon iPhoneLe 18 nov. 2022 à 12:14, Vuk Vasić ***@***.***> a écrit :﻿
We have a library that uses `Antlr.Runtime.Standard 4.8.0 and the one that uses 4.11.0. Unforecently those two are crashing because of following error:
[2022-11-18 11:09:12Z ERR] Something went wrong: System.TypeInitializationException: The type initializer for 'ExpressionAntlrLexer' threw an exception.
---> System.MissingMethodException: Method not found: 'Antlr4.Runtime.Atn.ATN Antlr4.Runtime.Atn.ATNDeserializer.Deserialize(Char[])'.
--- End of inner exception stack trace ---

There should not be a breaking change if only Minor version is increased

**Comment by vasicvuk** [comment]
Hi @ericvergnaud  Then you should change your versioning. Because currently, I cannot have two libraries that use ANTLR at the same time. One library references 4.8.0 and another 4.11.1, by SemVer those versions are compatible but in your case, they are not and we see an error in Runtime, which can cause big issues on prod environments.

**Comment by ericvergnaud** [comment]
I believe the official way to deal with these issues is by using WinSxS ?Envoyé de mon iPhoneLe 18 nov. 2022 à 13:07, Vuk Vasić ***@***.***> a écrit :﻿
Hi @ericvergnaud  Then you should change your versioning. Because currently, I cannot have two libraries that use ANTLR at the same time. One library references 4.8.0 and another 4.11.1, by SemVer those versions are compatible but in your case, they are not and we see an error in Runtime, which can cause big issues on prod environments.

**Comment by vasicvuk** [comment]
@ericvergnaud  I am not sure what you mean If you mean Side by side Windows? I am not using Windows at all. We use Linux containers and we have a microservice that currently relies on two libraries both using ANTLR within their codebase. One of them now crashes because of incompatibility.

**Comment by ericvergnaud** [comment]
Bumping the major version number wouldn't solve your problem (which is addressed by WinSxS, by java modules, but is a nightmare with python and nodes).
So I guess your only option is to require an upgrade of the library that uses 4.8.0.
I suggest that you also file a bug with Microsoft such that they provide SxS on Linux ?

**Comment by vasicvuk** [comment]
@ericvergnaud  Can you provide a link to this "WinSXS" because I am not sure what are you referring to?

Bumping a Major will resolve my problem, because the build will fail, and I wouldn't have a nonworking library in a running state. Then one library will reference one major version and another will reference a non-compatible major version, in the build process, i will get an error in incompatibility.  Now the build is a success.

**Comment by ericvergnaud** [comment]
https://learn.microsoft.com/en-us/windows/win32/sbscs/about-side-by-side-assemblies-￼
About Side-by-Side Assemblies - Win32 apps
learn.microsoft.com

Sorry if I sound a bit harsh, but wouldn’t your build also fail if you had proper integration tests in place ?
Sounds like your strategy relies on assumptions (every piece of code complies with unofficial semver) rather than facts (actually running the assembled code)...

**Comment by ericvergnaud** [comment]
We support 10 language targets, and a unique feature of ANTLR4 is cross-language compatibility.

As a result, ANTLR versioning strategy is as follows:
 - we release all targets whenever one changes, so can’t follow a per target versioning strategy (which is what you are expecting).
 - If we were to bump the major number with each breaking runtime change, there would be much more noise…
 - we only increase the major version number when we change the behavior of the grammar

Please enhance your test suite to cater for the above.

n.b.: backwards incompatibility is NOT a security issue.

**Comment by vasicvuk** [comment]
@ericvergnaud I didn't say it is. You read what you want to read, and don't look at anything from a bigger picture :). I just said that tools that do Security Component analysis will automatically update the dependency because there are no breaking changes and reference Dependabot as an example, the other one is NPM Audit, but there are so many more tools that rely on SemVer as standard.

No .NET developer will agree with the versioning strategy you currently have.

In the end, it's simple you follow Semantic versioning as standard or you don't.  If not this should be clear in the README so that other people know that they are dealing with an unstable library with breaking changes on each release, as the truth is that there is a breaking change on every release.

**Comment by ericvergnaud** [comment]
Please submit a PR for upgrading the README ?

**Comment by ericvergnaud** [comment]
No worry, closing.
