### ISSUE TITLE
`getPositionInLine()` not available for C# target

### ISSUE THREAD

**Issue by stanle-cs** [antlr/antlr4#3987]
Target: C#
Smallest possible grammar: `getPositionInLine() == 0`, or use the `PGN.g4` grammar file.
Expectation: receive the position in line (for example, to check for the first in line)
Actual: error saying that `getPositionInLine()` is not defined.
Comment: I actually searched through the repo and realized that `getPositionInLine()` is not defined anywhere for C#?

**Comment by kaby76** [comment]
Try [Column](https://github.com/antlr/antlr4/blob/47415e33c366cd9695d5c7e2586424692492deed/runtime/CSharp/src/Lexer.cs#L360).

**Comment by stanle-cs** [comment]
It works, but this breaks compatibility between the Java and the C# target, meaning that I can't use a general grammar without knowing if it's from C# or Java :(

**Comment by kaby76** [comment]
If you examine the naming constraints across all targets, you will discover that there cannot be a universally shared naming scheme in the target language for all targets (e.g., Go requires a capitalized name to be visible outside the class; properties in Java begin with 'get'). The problem is that there is no abstract language in actions that is translated to all targets and likely never be provided in Antlr. What would this abstract language be? What programming support would there be for this new, universal language?

Instead you can use "target agnostic format", which pushes the entire action code into a method of the target language. You can then write a base class for the targets you are interested in in the target language. Note, C++ requires a '->' deref operator to call the method on the base class, but you can use the "translateGrammar.py' trick to modify per target.

Take a look at the plsql grammar in the grammars-v4 repo for an example.

**Comment by stanle-cs** [comment]
I see, thank you for the notes. I'll probably open an issue on the grammars-v4 repo instead and suggest a change to the `PGN.g4` grammar that will make it more language agnostic.
