### ISSUE TITLE
[QUESTION] Javascript code patterns for producing custom JSON AST directly from grammar file

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [antlr/antlr4#4157]
Is it possible with grammar pattern like one below to create AST? If so, I would appreciate some code patterns/examples to access each matching blocks and information about where it starts and where it ends in input text

```antlr4
grammar Comment;


comment: '/*' (comment_text | new_line)* '*/' {
    const start = some_code_that_does_get_me_index_of_starting_slash;
    const end = some_code_that_does_get_me_index_of_ending_slash + 1;

    const content = some_code_that_will_let_me_retrieve_array_of_objects__comment_text__new_line;

    return {
        type: "comment",
        content,
        start,
        end
    };
};

comment_text: ~('*/' | '\r' | '\n')+ {
    const start = some_code;
    const end = some_code;

    return { 
        type: "text",
        subtype: "comment",
        start,
        end
    };   
};

new_line: '\r\n' | '\n'{
    const start = some_code;
    const end = some_code;

    return { 
        type: "new_line",
        start,
        end

    };   
};

```

**Comment by ericvergnaud** [comment]
Every recognized token conveys its type, start, stop and text (via a call). Grammar rules all have a context which provides the details you are looking for.
That said, it's much easier to implement the above using a listener after the code is parsed than by using inline code whilst parsing.
It's also better because the parsing is guaranteed to 'succeed' i.e. not crash.

**Comment by DanielMazurkiewicz** [comment]
Thanks!
