### ISSUE TITLE
Unable to post messages to ANTLR google groups - messages immediately deleted. 

### ISSUE THREAD

**Issue by raffian** [antlr/antlr4#4165]
I apologize for posting this question but I don't know where else to turn for assistance.

I subscribed to the ANTLR mailing list at **https://groups.google.com/g/antlr-discussion**, but every time I post a new message it gets deleted within seconds. At first I assumed my post got deleted for having a link - though it was a github link, and being a new member posting for the first time. I removed the link and tried again, but the message was again deleted. I then posted a simple message asking for help from the group, but even _that_ was deleted.  Bewildering and strange, to say the least. I checked my email for spam folders for confirmation email of any sort from the group but found nothing.

The group has no email, no admin to contact, nothing.
Again, my apologies but I don't know where else to go for help.

**Comment by jimidle** [comment]
I have seen this complain come in from quite a few Google groups lately. It seems that there is something wrong with Google groups and that this is happening on many forums. We may be seeing the end of Google groups. 

I don't think there is much we can do about it. Have you tried Stack Overflow?

**Comment by raffian** [comment]
My original question will likely elicit debate and subjective answers, so it's not suitable for StackOverflow.
ANTLR is such a vibrant community of contributors and developers, it's a shame I can't collaborate with them.

**Comment by kaby76** [comment]
I noticed this, too, in some of my posts to that group. I thought I was the only one black-balled. Perhaps it was deleted by Google or by explicitly by someone. We cannot say.

Feel free to post questions and comments like these in the [Discussion section on this repo](https://github.com/antlr/antlr4/discussions) or other of the antlr/ repos. If it's a specific question on a grammar in grammars-v4, please post over there so we can track and fix the grammar. I fully support your effort to collaborate.

People on StackOverflow downvote and close off any questions that aren't a detailed freshman-oriented coding question. I think this a shame. Also, I am against downvoting on SO because people get offended, and it seems the website has devolved into a popularity contest of accumulating points to look smart.

As my father--a well-known researcher and medical school professor--would say, people don't like questions.

**Comment by raffian** [comment]
@kaby76   Thanks for the discussions link - I didn't know that place existed. 👍
