### ISSUE TITLE
Typescript tsconfig.json error in node package. 

### ISSUE THREAD

**Issue by sudosu98** [antlr/antlr4#4280]
When i use the antlr4 npm package the tsconfig.json throws an error `Cannot find type definition file for 'node'.` Although I have included @types/node and @types/antlr4. I am using antlr4 v4.13.0.

![Screenshot from 2023-05-23 10-51-30](https://github.com/antlr/antlr4/assets/76874403/35c77fa9-30a3-4199-bc28-2205870f8b99)

**Comment by kaby76** [comment]
The way I do this is with a stripped-down tsconfig.json (see [tsconfig.json from the grammars-v4 build](https://github.com/antlr/grammars-v4/blob/4ee2f74c11722d0b7d6c52cc6a86d7f2564fe11c/_scripts/templates/TypeScript/tsconfig.json)), and a package.json with the package references (see [package.json from the grammars-v4 build](https://github.com/antlr/grammars-v4/blob/4ee2f74c11722d0b7d6c52cc6a86d7f2564fe11c/_scripts/templates/TypeScript/package.json)).

The instructions for the [Typescript target](https://github.com/antlr/antlr4/blob/master/doc/typescript-target.md) are insufficient. I am no expert on TS, and ChatGPT answers don't usually work. It took me months to devise build solutions for 8 antlr targets for grammars-v4. The build json files should be part of the documentation for the target because the build environment is at least as important--if not more so--than the driver source code. For Typescript, a "script" needs to be added to call the Antlr tool using [antlr4](https://github.com/antlr/antlr4-tools).

**Comment by sudosu98** [comment]
I noticed the my tsconfig was using 'commonjs' and antlr uses 'ESM' . I changed the module type for my project and it stopped throwing this error.

**Comment by kaby76** [comment]
> I noticed that my tsconfig was using 'commonjs' and antlr uses 'ESM' . I changed the module type for my project and it stopped throwing this error or maybe i also added the moduleResolution as 'Node'. It has stopped emitting that error for now.

Proof (again) that the build environment is at least as important--if not more so--than the driver source code.
