### ISSUE TITLE
Some rule names cause runtime errors in Python target

### ISSUE THREAD

**Issue by xmcp** [antlr/antlr4#4291]
[See this SO post](https://stackoverflow.com/questions/76353461/antlr4-python-target-not-working-with-some-special-rule-names?noredirect=1#comment134640110_76353461)

**Target:** `-Dlanguage=Python3`

**Grammar to reproduce:**

```
grammar Grammar;

program : state* EOF ;
state: 'break;' | 'continue;' | 'return;' ;
```

**Actual bahavior:**

The command `antlr4 -Dlanguage=Python3 Grammar.g4` silently successes, but the generated parser does not work. It will raise the below runtime exception:

```
Traceback (most recent call last):
  ...
  File ".../GrammarParser.py", line 96, in program
    self.state()
TypeError: 'int' object is not callable
```

**Expected behavior:**

Either the generated parser works, or the antlr4 command gives a warning about it.

**Bug cause:**

The rule name `state` conflicts with an internal field used by the generated target, leading to a naming conflict:

```python
class GrammarParser ( Parser ):
    def program(self):
        ...
            ...
                ...
                self.state = 4
                self.state()
                self.state = 9
                ...
```

Other rule names like `match`, `atn` or `consume` also lead to various runtime exceptions that looks confusing especially to beginners:

```
# match:
TypeError: GrammarParser.match() takes 1 positional argument but 2 were given

# atn:
AttributeError: 'function' object has no attribute 'states'

# consume:
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Since that the Python target [already renames keywords](https://github.com/antlr/antlr4/blob/873a01ca2939e623f396d356f9e903b9afd4ca32/tool/src/org/antlr/v4/codegen/target/Python3Target.java#L15), it should also rename internal names like `state` and `match`.

**Comment by kaby76** [comment]
Seeing that this may never be fixed, I have the beginnings of a [Trash](https://github.com/kaby76/Domemtech.Trash) script that finds parser symbol conflicts, at least for Python3. https://github.com/kaby76/g4-checks/blob/main/find-known-conflicts.sh. It does require version 0.20.24 of Trash tools.

**Comment by kaby76** [comment]
> @kaby76 this is not high priority, but it could probably be fixed by adding 'state' and reserved fields to the list of keywords. Feel free to give it a try.

Yes, it's an easy fix. But I am now thinking maybe these naming issues should be applied to the grammar. I usually see symbol conflicts when scraping a grammar (e.g., [JavaScript](https://262.ecma-international.org/13.0/#sec-grammar-summary)). A lot of CFGs don't follow the "uppercase start char = lexer symbol; lowercase start char = parser symbol" rule. Renaming is going to have to be done anyway. You just need a tool to detect these problems and rename them en masse. Scripts to do this are easy to write. Antlr can't do everything.

**Comment by kaby76** [comment]
Again, I recommend either imposing a naming convention for all symbols in the grammar, or using [Trash](https://github.com/kaby76/Domemtech.Trash) and the [find-known-conflicts.sh](https://github.com/kaby76/g4-checks/blob/main/find-known-conflicts.sh) script to find know symbol conflicts.

The script contains a copy of all the tables from the Antlr tool [codegen](https://github.com/antlr/antlr4/tree/master/tool/src/org/antlr/v4/codegen/target) code, plus a few that I added, including "state". The script flags symbol conflicts per-target. With the output, you can then rename the symbols accordingly.

Here is an example grammar and output from the script ran over the grammar.
```
grammar Foobar;
start : A* B NULL* state+ EOF;
NULL: 'null';
state: State;
State : 'state';
A: 'a';
B : 'b';
```
```
$ bash /c/Users/Kenne/Documents/GitHub/g4-checks/find-known-conflicts.sh Foobar.g4
Arguments were provided.
Finding useless parentheses in grammars...
CSharp checks...
Cpp checks...
L2: start : A* B NULL* state+ EOF;
                 ^
L3: NULL: 'null';
    ^
Dart checks...
Go checks...
L2: start : A* B NULL* state+ EOF;
    ^
Java checks...
JavaScript checks...
PHP checks...
Python3 checks...
L2: start : A* B NULL* state+ EOF;
                       ^
L4: state: State;
    ^
TypeScript checks...
06/07-14:21:06 ~/test/grammars-v4/x
```
The main problem in programming symbol conflicts is that the list is ever-changing. We don't know all the conflicts. For Cpp, it's impossible to predict conflicts because the generated code could be messed up via a macro from a `#include` header prior to including the header file for the parser or lexer.
