### ISSUE TITLE
Visitor Pattern in Golang

### ISSUE THREAD

**Issue by mkohlhaas** [antlr/antlr4#4395]

**Comment by kaby76** [comment]
Try implementing a dispatch routine. E.g.,
```
func (v *Visitor) Visit(tree antlr.ParseTree) any {
    switch val := tree.(type) {
    case *parser.ProgContext:
        return v.VisitProg(val)
    case *parser.DeclContext:
        return v.VisitDecl(val)
    case *parser.ExprContext:
        return v.VisitExpr(val)
    }
    return 0
}
```

**Comment by mkohlhaas** [comment]
There is already a Visit method in the base class which I use and should be used.

**Comment by kaby76** [comment]
> There is already a Visit method in the base class which I use and should be used.

Of course. The Antlr Visitor code doesn't work. Likely for Listeners as well.

https://github.com/antlr/antlr4/issues/2504
https://github.com/antlr/antlr4/issues/3265
https://github.com/antlr/antlr4/discussions/3812
https://github.com/antlr/antlr4/issues/1843

But, you asked: "Anyone [have] any idea how the visitor pattern should work in Go?". I am just saying, that if you are trying to get something to work now, then you might want to give that a try.

**Comment by mkohlhaas** [comment]
There are several projects using the listener interface without any issues.

@jimidle wrote an email to me saying there should be no bugs in the visitor pattern.

If it's a bug I guess it's even a bug in Golang. The behavior doesn't make much sense to me. But I'm a Golang newbie. 

So I'm just waiting for his reply. If the visitor pattern does not work I'll use neither the listener nor the visitor pattern. Instead I'll go just for the lexer and parser.

Workaround for the visitor pattern would be:
```golang
func (v *Visitor) Visit(tree antlr.ParseTree) any {
    return tree.accept(v)
}
```

Which wouldn't be too bad, actually. But I hate workarounds.

Thanks @kaby76 for your support. L

I like your Antlr4 🗑️ command tools btw.

**Comment by kaby76** [comment]
I think an end-to-end example is in order. I could not get Antlr Visitors to work unless I do the following:
* Define Visitor as you describe:
    ```
    type Visitor struct {
        parser.BaseExprVisitor
    }
    ```
* Define Visit() as you describe:
    ```
    func (v *Visitor) Visit(tree antlr.ParseTree) any {
        return tree.Accept(v)
    }
    ```
* Define each and every Visit...() function:
    ```
    func (v *Visitor) VisitProg(ctx *parser.ProgContext) any {
        fmt.Println("VisitProg")
        return v.VisitChildren(ctx)
    }

    func (v *Visitor) VisitDecl(ctx *parser.DeclContext) any {
        fmt.Println("VisitDecl")
        return v.VisitChildren(ctx)
    }

    func (v *Visitor) VisitExpr(ctx *parser.ExprContext) any {
        fmt.Println("VisitExpr")
        return v.VisitChildren(ctx)
    }
    ```
    In other words, the generated Visit...() functions do not work:
    ```
    func (v *BaseExprVisitor) VisitProg(ctx *ProgContext) interface{} {
        return v.VisitChildren(ctx)
    }

    func (v *BaseExprVisitor) VisitDecl(ctx *DeclContext) interface{} {
        return v.VisitChildren(ctx)
    }

    func (v *BaseExprVisitor) VisitExpr(ctx *ExprContext) interface{} {
        return v.VisitChildren(ctx)
    }
    ```
* Define VisitChildren(), because the default implementation is "return nil".
    ```
    func (v *Visitor) VisitChildren(tree antlr.RuleNode) any {
        n := tree.GetChildCount()
        for i := 0; i < n; i++ {
            c := tree.GetChild(i)
            val := c.(antlr.ParseTree)
            _ = v.Visit(val)
        }
        return 0
    }
    ```
    Note, this implementation does not "sum" the results of visiting the children, nor does it "short-circuit" the tree walking.

**Comment by jimidle** [comment]
I use both. I have not had time to look at what is happening here, but you
don’t need to implement all funcs. Just the ones you need.

I do wish to make some improvements to the way variables are accessed. But
I have not had time to do so. It does all work though. If you are new to
go, then it might not be obvious. I should create some example projects to
help.

Jim

**Comment by mkohlhaas** [comment]
>  I should create some example projects to help.

That would be great as I couldn't find any sample code.

Thanks. 🙏

**Comment by kaby76** [comment]
The code attached implements a Visitor for the Java and Go targets. I have one for CSharp, but it behaves like the Java target, so I haven't included it. The applications are generated for Windows Msys2.

In this example, I define all Visit...() methods/func except ProgVisit(). 

For Java, the tree walker visits the entire tree, which you can see by the output for DeclVisit() and ExprVisit().

For Go, the visitor does not visit the children because "func ProgVisit()" is commented out. If "func ProgVisit()" is uncommented, the entire tree is traversed.
```
08/28-02:29:36 ~/issues/antlr-4395/x/Generated-Java
$ ls
build.sh  ErrorListener.java  ExprBaseVisitor.java  makefile                        perf.sh  Test.java  test1.txt
clean.sh  Expr.g4             ExprVisitor.java      MyDiagnosticErrorListener.java  run.sh   test.sh    Visitor.java
08/28-02:29:37 ~/issues/antlr-4395/x/Generated-Java
$ make
bash build.sh
08/28-02:29:45 ~/issues/antlr-4395/x/Generated-Java
$ bash run.sh test1.txt
visitDecl
visitDecl
visitExpr
visitExpr
visitExpr
visitExpr
visitExpr
visitExpr
visitDecl
Java 0 test1.txt success 0.011
Total Time: 0.115
08/28-02:30:16 ~/issues/antlr-4395/x/Generated-Java
$ cd ..
08/28-02:30:19 ~/issues/antlr-4395/x
$ cd Generated-Go/
08/28-02:30:23 ~/issues/antlr-4395/x/Generated-Go
$ ls
build.sh  clean.sh  go.mod  go.sum  makefile  parser/  perf.sh  run.sh  Test.go  test.sh  test1.txt
08/28-02:30:26 ~/issues/antlr-4395/x/Generated-Go
$ make
bash build.sh
08/28-02:30:32 ~/issues/antlr-4395/x/Generated-Go
$ bash run.sh test1.txt
Go 0 test1.txt success 0.000
Total Time: 0.001 s
08/28-02:30:40 ~/issues/antlr-4395/x/Generated-Go
$
```

Here are the two applications in .zip files.

[Generated-Java.zip](https://github.com/antlr/antlr4/files/12451058/Generated-Java.zip)
[Generated-Go.zip](https://github.com/antlr/antlr4/files/12451059/Generated-Go.zip)

**Comment by mkohlhaas** [comment]
Nice. But this is not the visitor pattern:

```go
func (v *Visitor) Visit(tree antlr.ParseTree) any {
    return tree.Accept(v)
}
```

The method from the base class should be used.

**Comment by kaby76** [comment]
> Nice. But this is not the visitor pattern:
> 
> ```go
> func (v *Visitor) Visit(tree antlr.ParseTree) any {
>     return tree.Accept(v)
> }
> ```
> 
> The method from the base class should be used.

That function is essentially the code that [you gave above](https://github.com/antlr/antlr4/issues/4395#issuecomment-1694786752)!

```
func (v *Visitor) Visit(tree antlr.ParseTree) any {
    return tree.accept(v)
}
```
But, besides, the implementation I made is equivalent to the "base class" implementation except for the function receiver. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Go/antlr/v4/tree.go#L61

Doing what you suggest--commenting out the Visit() implementation in Test.go that I made--does not work either.

It's moot anyway because the overarching fact remains: VisitChildren() is unimplemented, yet the Antlr tool generates code with VisitChildren() function calls.

**Comment by mkohlhaas** [comment]
> It's moot anyway because the overarching fact remains: VisitChildren() is unimplemented, yet the Antlr tool generates
> code with VisitChildren() function calls. The Visitor code can only work with all the func's implemented as 
> https://github.com/antlr/antlr4/issues/4395#issuecomment-1694846647.

It's not moot. It's a bug!

**Comment by kaby76** [comment]
> > It's moot anyway because the overarching fact remains: VisitChildren() is unimplemented, yet the Antlr tool generates
> > code with VisitChildren() function calls. The Visitor code can only work with all the func's implemented as
> > [#4395 (comment)](https://github.com/antlr/antlr4/issues/4395#issuecomment-1694846647).
> 
> It's not moot. It's a bug!

I really don't know what you are referring to. What is "it" in "It's a bug!"??
