### ISSUE TITLE
Java packages directory structure is not adding automatically

### ISSUE THREAD

**Issue by dzavodnikov** [antlr/antlr4#455]
When I want to generate lexer/parser into package `a.b.c` I am using following code:

```
$ java -cp antlr-4.1-complete.jar org.antlr.v4.Tool -o src -package a.b.c A.g4
```

and get generated parser and lexer into `src` directory:
- `src/ALexer.java`
- `src/AParser.java`

and etc. But I expect:
- `src/a/b/c/ALexer.java`
- `src/a/b/c/AParser.java`

To get it I should duplicate structure informatio into `-o` option:

```
$ java -cp antlr-4.1-complete.jar org.antlr.v4.Tool -o src/a/b/c -package a.b.c A.g4
```

But It is not so useful as It can be.

**Comment by ctubbsii** [comment]
This situation is worse with the antlr4-maven-plugin, because it automatically adds the outputDirectory to the build class path (since it contains generated sources), but that directory can't be properly viewed as a source directory in an IDE, since the classes don't follow Java's rules about how to organize source files into package folders.
