### ISSUE TITLE
[go] performance downgrade a lot after upgrade antlr from 4.9 to 4.13.1

### ISSUE THREAD

**Issue by longjiquan** [antlr/antlr4#4613]
Hello, guys, thanks for the awesome project, it saved a lot of time for us to build a parser. Recently, I tried to upgrade the antlr version from 4.9 to 4.13.1, and I followed the https://github.com/antlr/antlr4/blob/master/doc/go-target.md to do this. However, after both the antlr runtime and generated code was upgraded to 4.13, we didn't gain performance improvement. The flamegraph of pprof indicated that the newer version need more time to do the parsing, most of cpu time was consumed by the `sync.Mutex` inner `ATN.NextTokensNoContext`. I'm very confused about this because in fact a parser won't be used in multiple goroutines in our scenario. Can anyone give me some suggestions?

Version 4.9, the parsing cost 25.42% of cpu:
![image](https://github.com/antlr/antlr4/assets/31589260/d9925786-f6bb-49fd-9549-2ed1b63c76ee)

Version 4.13, the parsing cost 35.99% of cpu:
![image](https://github.com/antlr/antlr4/assets/31589260/eae06e28-e222-4ef7-a947-bcb3e76b5fb4)

**Comment by jimidle** [comment]
I would need to see your grammar. There are a couple of small performance improvement patches that I intend to release very shortly. But I had debated just not allowing multiple go routines , but people said they used them. I did some work on a build configuration for this, but did not finish it yet.

However, benchmarks are fickle. So:

Did you first run one parse without measuring to load the ATNs etc? You cal also cause it to do that before parsing.=, but that is the easiest way. It looks like you have have done that given the elapsed times?
The version you were running was actually very broken. You are lucky it ran I think. I do not remember having to put that mutex in, but if I did, it is because it was needed in comparison to the Java target. 
However, it looks like the one you point out is coming from the ErrorStrategy? Are you parsing things in error?

This version definitely performs much better, but if your grammar is very ambiguous, then all bets are off. The previous runtime probably did not do half the work it should have done.

If you supply your grammar, then I can take a look.  But are you trying SLL parsing first? And using the DiagnosticErrorListener to work out where your grammar might be flakey?

I will also check to see what state my single threaded grammar was in.

FInally, you are using the latest Go compiler?

**Comment by longjiquan** [comment]
Thanks for the very quick reply, @jimidle . My grammar can be found at https://github.com/milvus-io/milvus/blob/master/internal/parser/planparserv2/Plan.g4. This version has not been launched in our production environment yet, we just compared it to see if any performance improved.
For other questions you mentioned:
1. We don't parse things in error, the syntax is correct.
2. Yes, we used an error listener, and it can be found at https://github.com/milvus-io/milvus/blob/master/internal/parser/planparserv2/error_listener.go.
3. Go version: go version go1.20.7 linux/amd64.

**Comment by jimidle** [comment]
Please note new release:

https://github.com/antlr4-go/antlr/releases/tag/v4.13.1

This allows you to turn off mutexes with the build tag `-tags antlr.nomutex`

I will check your grammar and listener in a few days. But in the meantime, upgrade your go to the latest and check your grammar for efficiency and ambiguities.

**Comment by jimidle** [comment]
I took a Quick Look at the grammar that’s your issue. It is very ambiguous
and days not use left revision well for precedence. Binary ops are usually
higher precedence than everything else other than patens.

So the angle is likely calling your listener a ton of times my to try and
tell it about about, which it ignores. The listener then looks at tokens
and uses the locks. The new runtime will help with locks but don’t just
stop there. Let’s redo your grammar so that you don’t have the issue in the
first place.

Jim

**Comment by longjiquan** [comment]
Sorry for the late reply, I'm not feeling well these days and had some rest.
Thanks for your suggestions about how we avoid the mutex, and I'll benchmark the performance with this feature.
Could you give some suggestions about how I can reduce the ambiguity of the grammar?
Hope you will have a good weekend!

**Comment by jimidle** [comment]
@parrt This can be closed. The grammar was the problem, not ANTLR or the Go runtime.

**Comment by longjiquan** [comment]
Thanks a lot for the very detailed suggestions, @jimidle . I'll have a try to fix it.
