### ISSUE TITLE
Memory Leak in PredictionContextCache

### ISSUE THREAD

**Issue by mikedehaan** [antlr/antlr4#499]
After using an antlr generated parser to process several files, the JVM eventually throws an out of memory exception. Analyzing the heap show the PredictionContextCache containing a HashMap with over 1 million items. There needs to be some (hopefully thread safe) way to clear this cache between runs.

https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/atn/PredictionContextCache.java#L40-66

**Comment by danielsun1106** [comment]
@parrt @sharwell
Hi Terence, Sam
Is it possible to make DFAState.edges hold SoftReference<DFAState> instances and make PredictionContextCache have some cache eviction policy(e.g. LRU)?

**Comment by danielsun1106** [comment]
@parrt @sharwell
Hi Terence, Sam
Is it possible to make DFAState.edges hold SoftReference<DFAState> instances and make PredictionContextCache have some cache eviction policy(e.g. LRU)?

**Comment by sharwell** [comment]
@danielsun1106 It would be difficult to use a cache eviction policy for `PredictionContextCache` that only partially clears it. One purpose of the cache is to reduce the number of times these instances get referenced.

The use of `SoftReference` instances in `DFAState.edges` would result in a 30-byte memory overhead *per edge* in the DFA relative to what we have now (54 bytes on 64-bit JVMs where compressed OOPS are not enabled).

**Comment by danielsun1106** [comment]
IMO, the increased memory usage because of the use of SoftReference could be accepted than the OutOfMemoryError :)
As of the cache eviction policy, I tried to replace the default cache with the LRU  cache based on guava while developping the Groovy parser about some months ago, but the performance was not much improved...

@sharwell
Sam, could you help me to confirm whether PredictionContextCache instance holds any DFA data? In other words, any relationship exists between PredictionContextCache and DFA? There are 2 causes of OutOfMemory(PredictionContextCache and DFA cache), I wonder that any problem will occur if we resolve one of the two causes? Thanks in advance.

**Comment by danielsun1106** [comment]
IMO, the increased memory usage because of the use of SoftReference could be accepted than the OutOfMemoryError :)
As of the cache eviction policy, I tried to replace the default cache with the LRU  cache based on guava while developping the Groovy parser about some months ago, but the performance was not much improved...

@sharwell
Sam, could you help me to confirm whether PredictionContextCache instance holds any DFA data? In other words, any relationship exists between PredictionContextCache and DFA? There are 2 causes of OutOfMemory(PredictionContextCache and DFA cache), I wonder that any problem will occur if we resolve one of the two causes? Thanks in advance.

**Comment by sharwell** [comment]
@danielsun1106 There can easily be hundreds of thousands or even millions of `DFAState` instances, so the difference could be hundreds of MiB in a running application. A `PredictionContext` is a key element of an `ATNConfig` instance, and a `DFAState` has one or more `ATNConfig` in it (aside from `DFAState.EMPTY`). These instances are required for the ability of the parser to resume DFA construction from a point where it previously left off. Without them, if a missing edge is encountered during lookahead the prediction algorithm would need to rewind the input all the way to the start of the current prediction and recreate all the edges leading to the missing edge.

The `PredictionContextCache` caches `PredictionContext` instances to eliminate duplicate instances in the DFA. In the reference release, this cache is a close approximation to the optimal elimination of duplicates. In my optimized fork it is a fully-reduced (optimal) graph.

For reference, are you using the reference release or my fork for your evaluation? The most substantial work in my fork is on memory reduction. It's not uncommon to see 100:1 ratios in memory requirements between the two.

**Comment by danielsun1106** [comment]
@sharwell 
While developping the Groovy parser, I used both version of Antlr4(reference release and your optimized release), which both have the OutOfMemoryError if we do not clear cache or recreate cache.

When we try to apply two-stage parsing strategy, the reference release hangs but the optimized release is quite efficient, which is very impressive to me.

It's pity that the optimized release have to deserialize the ATN string by call the following code to avoid OutOfMemoryError. `new ATNDeserializer().deserialize(GroovyLangLexer._serializedATN.toCharArray())`

As a result, the performance of optimized release(applied two-stage parsing strategy) is almost same with the reference release(not applied two-stage parsing strategy). I wish optimized release would provide some constructor like the following ones in the future, then we could create decisionToDFA array from the deserialized ATN 
```java
public ParserATNSimulator(Parser parser, ATN atn, DFA[] decisionToDFA, PredictionContextCache sharedContextCache)
public LexerATNSimulator(Lexer recog, ATN atn, DFA[] decisionToDFA, PredictionContextCache sharedContextCache)
```

As of the usage of memory, how about wrapping the DFA with a DfaWrapper. The count of DFA is not very many(about `_ATN.getNumberOfDecisions()`), the reference code is shown as follows
```java
class DfaWrapper extends DFA {
      private SoftReference<DFA> dfaSR
      private ATN atn;
      private int decision;
      public DfaWrapper(ATN atn, int decision) {
             this.dfaSR = new SoftReference(atn.getDecisionState(decision), decision);
             this.atn = atn;
             this.decision = decision;
      }
      public DFA getDFA() {
              DFA dfa = dfaSR.get();
              if (null != dfa) return dfa;

              synchronized (this) {
                   if (null == dfaSR.get()) {
                            dfaSR = new SoftReference(atn.getDecisionState(decision), decision);
                   }

                   return dfaSR.get()
              }
      }

      // deletate DfaWrapper' methods to DFA's methods
      public List<DFAState> getStates() {
            return this.getDFA().getStates();
      }
      // ...
}

// in the generated GroovyParser
// create the _decisionToDFA 
	static {
    		_decisionToDFA = new DfaWrapper[_ATN.getNumberOfDecisions()];
    		for (int i = 0; i < _ATN.getNumberOfDecisions(); i++) {
			        _decisionToDFA[i] = new DfaWrapper(_ATN.getDecisionState(i), i);
    		}
	}
```

ps: The brand new groovy parser's repository is hosted at https://github.com/danielsun1106/groovy-parser
(Currently I am using the reference release and plan to migrate to the optimized release later to gain better performance)

**Comment by hsyuan** [comment]
@parrt  @sharwell 
We have consistently seen the generated parser swallows up a lot of memory in our database system, because of the global cache in `DFA.states` and `PredictionContextCache`.
```java
public class XXXParser extends Parser {
	static { RuntimeMetaData.checkVersion("4.5.3", RuntimeMetaData.VERSION); }

	protected static final DFA[] _decisionToDFA;
	protected static final PredictionContextCache _sharedContextCache =
		new PredictionContextCache();
...
}
```
![image](https://user-images.githubusercontent.com/15352793/86536315-34572480-beac-11ea-8576-30a4cc72e00b.png)

![image](https://user-images.githubusercontent.com/15352793/86536317-37eaab80-beac-11ea-9c7d-7d09958922ff.png)

I think switching to WeakHashMap (with Dummy value) or Guava WeakInterner will solve the memory issue. Although they can introduce a little bit of memory overhead because of the `Reference`, the cached object will be garbage collected when it is not strongly referenced anymore, better than running out of memory. 

Thoughts?

**Comment by parrt** [comment]
@hsyuan well we can't really make these DFA states weak refs I don't think and would be a huge change, which I can't consider at this time.

**Comment by parrt** [comment]
BTW, I'm assuming you know to clear the cache?

**Comment by hsyuan** [comment]
Thank you for your quick response, @parrt.

> I'm assuming you know to clear the cache?

I am not sure if I understand your question correctly. Clearing the cache is the last thing I'd like to do, because that may impact the performance.

> we can't really make these DFA states weak refs I don't think and would be a huge change
By 'huge change', do you mean it is a breaking change, not because the amount of code to be changed? I see `DFA.states` is public and `PredictionContextCache.cache` is protected.

**Comment by parrt** [comment]
I'd graph the memory growth and clear if it gets close to too big. not sure why it's growing forever but it could with huge grammar (SQL?) and long running server.  Huge change means possibly breaking, possibly slower, and too much for me to consider doing.

**Comment by hsyuan** [comment]
> not sure why it's growing forever but it could with huge grammar (SQL?) and long running server. 

Correct. Tons of huge SQL queries and long running server.

**Comment by hsyuan** [comment]
Looks like Presto faces similar issue: https://github.com/prestosql/presto/pull/3186

**Comment by xuanziranhan** [comment]
We have long running servers with large queries too. Wondering if we'd like to support external cache, or disable cache options?

**Comment by sharwell** [comment]
@xuanziranhan Typically when the DFA is getting very large, one or more rules in the DFA is requiring long lookahead to make the decision. Restructuring the rules to reduce lookahead in those cases could also reduce the DFA size.
