### ISSUE TITLE
Parameterized Stateless Visitors

### ISSUE THREAD

**Issue by jfallows** [antlr/antlr4#641]
The generated visitor classes are already parametrically typed to produce a strongly-typed result, but they require a new instance of the visitor to be created for each traversal.

By applying a parameterized visitor pattern, stateless visitors can be shared across threads and nested visitors with a different return type do not need to be constructed to propagate state that can now be passed as a parameter.

For example:

``` Java
public interface ParseTreeVisitor<R, P> {
  R visit(@NotNull ParseTree tree, P parameter);
  R visitChildren(@NotNull RuleNode node, P parameter);
  R visitTerminal(@NotNull TerminalNode node, P parameter);
  R visitErrorNode(@NotNull ErrorNode node, P parameter);
}

public interface ParseTree extends SyntaxTree {
  <R,P> R accept(ParseTreeVisitor<? extends R, ? extends P> visitor, P parameter);
}
```

This approach has been applied to the [ElementVisitor API in the Java7](http://docs.oracle.com/javase/7/docs/api/javax/lang/model/element/ElementVisitor.html) traversal of Java source code.

Recommend providing the ability to use the parameterized stateless visitor approach for ANTLR4 grammars.

**Comment by otykier** [comment]
_Very_ late to the party, but I faced the same issue in the ANTLR C# target. What I did, although not pretty, was to tack on a new property to my base parser context class, so that I can pass state around inside the visitor. This was possible since the C# target generates a `partial` class for all derivatives of `ParserRuleContext`. So in my example:

```csharp
public partial class MyBaseExprContext   // In the generated file, this is defined as deriving from ParserRuleContext
{
    public object State { get; set; }
}
```

In my visitor, I can then assign values to this property before calling VisitXXX methods while building my AST:

```csharp
public override ExpressionNode VisitMyBaseExpr(MyBaseExprContext context)
{
    var child = (context.GetChild(0) as MyBaseExprContext);
    child.State = "..." // Set whatever state I need...
    Visit(child);
}
```
In my grammar, the AST I'm building aligns quite nicely with the CST generated from the parser, so this approach works, but it can probably not be applied in general.

**Comment by nielsbasjes** [comment]
I've been playing around with the Antlr4 code a bit and I took this approach (Java only):
1) Create a modified Java.stg and use that during code generation
2) Modify a small number of the Java runtime to match the generic parameter changes).
3) Package this into a single library so that using it is relatively easy.

That way most of the Antlr4 code is used as-is and my simply overriding some classes in the classpath you get the union of the base code and my modifications.

It is not backwards compatible but it seems to work for my use case.

https://github.com/nielsbasjes/antlr4-pvisitor

I would love feedback on this from you guys.

**Comment by deus777** [comment]
Reopening this issue with my solution in python, might be helpful to someone.

I had a similar requirement with a custom query tree at the top of the syntax and generated data further down the parse tree that was potentially too large for memory . The idea of having to build a new tree of a complex nested query passing it down to the data, aside from duplicating what antlr already does and being tedious and inefficient didn't appeal to me at all.

So rather than building a query tree and visiting the data generators to execute, I ended up converting the data to a list of python generators and passing them back up to the query. The query can then be executed in place with just a normal antlr visitor against the generators.

No supplemental data structures, no need for additional parameters in the visitor call

I thought it was a simple elegant pattern.

**Comment by ericvergnaud** [comment]
Hi,
Can you provide an example?

**Comment by deus777** [comment]
as an example I rewrote the grammar something along these lines

selectexpr : selectexpr SELECT? LPAREN selector RPAREN
           | selectexpr SELECT? opnot=NOT selector
           | selectexpr SELECT? selector AND selector
           | selectexpr SELECT? selector  OR  selector
           | selectexpr SELECT? selector
           | genexpr
           ;

the data was being generated several layers down in genexpr, which returned potentially huge lists. These function  now return a list of python generators through the standard visiting protocol and which I then have access to in the visitor method for selectexpr and can apply the boolean logic to the generators. So instead of trying to pass the logic down to the data I bring the data back up through python generators without making potentially huge lists or having to augment antlr visitor protocol or keep track of state etc.

**Comment by ericvergnaud** [comment]
And how does the visitor code look like ?

**Comment by deus777** [comment]
In this case selectexpr receives a list of generators  by calling visit(genexp) which are drained by  for x in gen loops and the local logic of selectexp is applied in the loop. you effectively have a window between code levels of the parse tree to pass data back and forth since python generators can be bi-directional. In this case the lower levels just yield data back up the tree, on demand. genexp generator function will have yield expression instead of a return expression. python takes care of the rest.

**Comment by ericvergnaud** [comment]
please provide a visitor sample rather than a description

**Comment by deus777** [comment]
roughly something like this

def visitorSelectexpr(...)

    ans = self.visit(ctx.genexpr)
    for items in ans:
           do something
...
def makedata(...)
      for  item in generate_dome_data:
                 yield item

def visitorGenexpr(...)
      .....
      ans = makedata( ...)
      ...
      return ans

python see the yield inside makedata and makes the function a generator.  the "ans= makedata()" doesnt actually do anything until it is triggered in the "for items in ans: " loop in visitorSelector, at which point makedata() start yielding items one by one.

normally you might something have

def makedata(...)
      for items in generated...
          list.append(item)
    return list


Instead visitorGenexpr actually returns a generator back up to the selectexpr visitor, rather than a list. It's possible to set this up as a co-routines and pass stuff back and forth, I didn't need to. a good reference here (http://www.dabeaz.com/coroutines/)

It's a bit like creating a wom hole between your nodes of the parse tree. hope that helps

**Comment by vrdhn** [comment]
Will this work
```
public class StatelessVisitor<T, S> extends {{ParserName}}BaseVisitor<T> {

    private final List<S> statesStack = new ArrayList<>(10);
    /**
     * In a normal visit*() function, call {@link ::state()} to get the current state.
     *
     * @return
     */
    protected final S state() {
        final int size = statesStack.size();
        return statesStack.get(size - 1);
    }

    /** Visit the subtree with given state. Note that it's prefectly
     * fine to call visit(ctx), if new state is not to be passed.
     */
    public final T visit(ParseTree tree, S state) {
        final int size = statesStack.size();
        // Note: using pointer equality here, as it's faster and works for the use case.
        final boolean newState = size == 0 || statesStack.get(size - 1) == state;
        if (newState) {
            try {
                statesStack.add(state);
                return visit(tree);
            } finally {
                statesStack.remove(size);
            }
        } else {
            return visit(tree);
        }
    }
}
```

**Comment by TheMinefighter** [comment]
I would very much like to see this implemented, as a visitor parameter would be great to store a scoped symbol table for example. Regarding the backwards compatibility I would consider adding a new switch beside -visitor, maybe called `-parameterizedVisitor` to generate these, so that these new visitors can coexist with the old ones, not breaking compatibility.

**Comment by jimidle** [comment]
Why would you not just inherit the base visitor and add a parameter to your
superclass?

**Comment by TheMinefighter** [comment]
@jimidle because I'd want the symbol table to be different between visit calls by the same visitor (which is not unusual when you nest symbol scopes). 
Inside a loop you have the iterator variable in scope, but not outside the loop. Therefore the parameter of the visitStatement would have to differ whether you are in the loop or not. Of course, you could have one visitor per scope or always load and store the current symbol table in a visitor variable but both are unaesthetic workarounds.

**Comment by TheMinefighter** [comment]
I am aware that that is a possibility.
