### ISSUE TITLE
Provide ANTLR 4.4 on Maven Central

### ISSUE THREAD

**Issue by voidengineer** [antlr/antlr4#675]
Hi there,

since you changed the build to bild.py artifacts are no longer published to Maven Central. That is really a PITA for those of us using maven to build their Java-projects.

Could you please somehow provide the artifacts on Maven Central again.

**Comment by bertramn** [comment]
Any update on getting the official antlr.org 4.4 pushed to central? Its really annoying given the latest Eclipse ANTLR plugin is already generating 4.4 antlr code and the runtime deps from central are only up to 4.3 basically failing to run any tests inside of Eclipse.

```
Caused by: org.antlr.v4.runtime.RuntimeMetaData$VersionMismatchException: 
   ANTLR Tool version 4.4 used for code generation does not match
   the current runtime version 4.3
```

**Comment by jimidle** [comment]
Ter/Sam,

Do you need me to make this happen? I think I still have the passwords etc
for the org.antlr  account at Sonatype unless we have changed from teh
account that I originally opened there.

Jim

**Comment by ericvergnaud** [comment]
Hi Jim,

thanks for your proposal.

The build methodology has significantly changed: from maven to python.
Terence has provided a bild.py and a bilder.by which are easier to manage.
We have reached a point where we are, using the above, able to install the various jars in a local repo.
We still need a bit of work to be done to deploy these to maven central.
There is also need a for help to make all this OSGI compliant.
So your help is definitely welcome.

Cheers,

Eric

**Comment by miho** [comment]
Hi all,

out of curiosity, is there a specific reason for not using gradle? It comes with maven support and works well for many projects.

Regards,
Michael

**Comment by whitten** [comment]
I have heard good things about gradle.
My expectation is that maven is the focus because it works with eclipse.
Does gradle?

Also I would expect that skills, time, and people to work are still being
gathered together.
Perhaps you can volunteer?

**Comment by ericvergnaud** [comment]
Hi,

right now, the discussion is not around the build itself but around publishing to maven central.
in the Java world, maven is the focus because it’s the widely dominant system for dependency management, thanks to the Nexus repos.
this is true for Eclipse, IntelliJ, Jenkins and any Java build tool.

however it would be good to have gradle experts look at what bild.py/bilder.py do and tell whether it can be achieved simply with gradle
given that both bild.py and gradle share the concept of an imperative build script, I don’t expect any reluctance

Eric

**Comment by miho** [comment]
Hi,

> right now, the discussion is not around the build itself but around publishing to maven central.

I get that. But Gradle solves both problems. It is compatible to Maven and Ant. It can declare dependencies to artifacts hosted on maven central or any other maven repo. And it can be used to publish to maven repositories. 

IDE adoption is quite good. Netbeans, Eclipse and IntelliJ provide plugins to load Gradle projects.

This builder.py thing looks like something tailored specifically for ANTLR and related projects.

I'm not a build system guru. But I really like Gradle and use it for most of my projects. I also upload stuff to Sonatype and other maven repositories. And I extend ANTLR classes and call ANTLR methods from Gradle scripts ;-)

**Comment by ericvergnaud** [comment]
Great!

You are welcome to propose a gradle build script.
Basically, simply implement all the steps implemented by bild/bilder and we can then evaluate how it fits the requirement.
:-)

Eric

**Comment by parrt** [comment]
Hi guys. I have looked at various build systems and find them hypercomplicated for what I need.

**Comment by bertramn** [comment]
What's wrong with `mvn clean install`? I have to agree with Jim, if it can't be checked out and imported into Eclipse/Netbeans/IntelliJ easily, its of no good use. Btw I neither have gradle nor python installed and never came across something I could not build using good old maven. Niels

**Comment by jimidle** [comment]
I think this is generally how people would feel.

However so long as the runtime and tool jars are available in Central it
does not affect too many people as few will be building ANTLR itself.

But if getting the artifacts in to Maven central in the first place is a
pain, then we will end up in the situation where Maven lags behind all the
time. That's why it should be as easy as:

 mvn deploy

and checking the boxes at the Sonatype web site. If it isn't right now,
then either the mvn configuration is wrong/gone off kilter or it has not
been kept up to date with the source code et and so you can only build it
with the python script. I am not sure where it is at.

Jim

**Comment by CzarScar** [comment]
I found that the jar in com.tunnelvisionlabs:antlr4:4.4 is not correct version. The 'com.tunnelvisionlabs:antlr4:4.4' jar does not contain a RuntimeMetaData.class,but this class is since version 4.3,and 'org.antlr:antlr4-runtime:4.3' jar contains it .So could you check it or provide the correct 4.4 in maven repo? Thanks

**Comment by sharwell** [comment]
@CzarScar The com.tunnelvisionlabs release is from a [fork of the project](https://github.com/sharwell/antlr4/releases/tag/4.4-opt) where the [`RuntimeMetaData` functionality needed to be removed](https://github.com/sharwell/antlr4/releases/tag/4.3-opt) because it didn't follow the compatibility policy for the fork. The fork ensures that a grammar compiled with 4.3 works with 4.4+ unless a breaking change is *absolutely required*. The `RuntimeMetaData` class on the other hand *forced* the code to stop working, even though there were no other reasons why it wouldn't run.

**Comment by parrt** [comment]
We are getting 4.5 release candidate 1 out the door. Once we get confidence in the release, we will deploy to maven central.

**Comment by parrt** [comment]
Howdy.  I pushed 4.5-SNAPSHOT to https://oss.sonatype.org/content/repositories/snapshots. can you guys check that antlr4-runtime and antlr4-master artifacts are available? thanks!
