### ISSUE TITLE
ANTLR generate code into incorrect path

### ISSUE THREAD

**Issue by dzavodnikov** [antlr/antlr4#683]
If I use following string to generate lexer and parser from grammar:

```
$ java -cp antlr4-complete-4.4-bin.jar org.antlr.v4.Tool -o src/my/package -package my.package MyGrammar.g4
```

code will be placed into correct path -- into `src/my/package` directory.
But if I use following string:

```
$ java -cp antlr4-complete-4.4-bin.jar org.antlr.v4.Tool -o src/my/package -package my.package grammars/MyGrammar.g4
```

code will be placed into `src/my/package/grammars` directory! Also one directory **grammars** will be added!

**Comment by gmai2006** [comment]
Hi Sam,
I totally agreed with Terence  and others.  The change would make easier to understand and save us lots unnecessary issue and workaround because of the implicit assumption by the Tool.  

Thanks for understanding and hope it will be included in the next version and thanks the team for this wonderful parser generation tool
Cheers,
Paul
