### ISSUE TITLE
Random ArrayIndexOutOfBounds exceptions coming from ParserATNSimulator

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#804]
It looks like a transient problem, even in the environment where we saw the issue originally it hasn't been reproducible. Only happens in our automation environment (rehat 5.7 running on open stack running on I dunno what) and only occasionally.

It happens in here:

```java
synchronized (from) {
    if ( from.edges==null ) { 
        from.edges = new DFAState[atn.maxTokenType+1+1];
    }   

    from.edges[t+1] = to; // connect
}   
```

so in some case `atn.maxTokenType+1 > t` must be true.   

I checked and it looks like the field "edges" is always protected by its parent `DFAState` object except for in one suspicious place where it appears to be guarded by an instance of `DFA` in `DFA.java`'s `setPrecedenceDfa` method.  (all in 4.3)

It would seem on the face of it that you need to synchronize inside `setPrecedenceDfa` on the `DFAState` rather than the `DFA` (or perhaps in addition too?).  

Maybe we should just add an assert there.   

```java
assert t +1 < from.edges.length : "array index out of bounds!, t = " + t + ", edges.length=" + from.edges.length;
```

And perhaps add something about which threads are active and their stacks if it fails?

**Comment by sharwell** [comment]
Since it's always possible for users to assign types to a token which fall outside the normal bounds defined by [`EOF`, `atn.maxTokenType`], the solution is to guard the assignment of the DFA edge. using the length of the `edges` array.

```java
int index = t + 1;
if (index >= 0 && index < from.edges.length) {
    // add the edge to the DFA
    from.edges[index] = to;
}
```

I had not observed the issue myself because one of the memory optimizations I needed required the inclusion of this range check quite a while back. Which brings us to the actual cause....

When we added code to generate rule bypass transitions during ATN deserialization, we allowed the deserializer to define tokens which are greater than `atn.maxTokenType`. When one of these edges is added to the DFA, the exception reported here gets thrown.

**Comment by parrt** [comment]
Wow! You found it. excellent. I'll explore when I finish class prep.

**Comment by ericvergnaud** [comment]
Not sure that’s the explanation:
 - such a guard is already in place just before the allocation and exception:
	if (from == null || t < -1 || t > atn.maxTokenType) {
		return to;
	}
 - the exception would occur deterministically

**Comment by sharwell** [comment]
@ericvergnaud makes a good point.

I looked at a few other possibilities but haven't found any clear problems so far. The two areas of focus for me are:

* The `s0` state for precedence DFAs, which uses an `edges` array indexed by precedence instead of `atn.maxTokenType`. However, this state is never added to the `states` map for the DFA so it will never be the target of a transition within the DFA.
* The `ERROR` state. If you ever fail to stop when the `ERROR` sentinel DFA state is reached, it will cause a big problem. You could add the following to `addDFAEdge`, but so far I couldn't find any way for this to occur.

    ```csharp
    assert from != ERROR;
    ```

**Comment by ericvergnaud** [comment]
Given the context in which it occurs, I don’t think the issue lies in the algorithm itself.

I’m more suspicious with the 2 different allocation strategies for edges depending on whether the DFA is a precedence one or not, especially given the below:

	if (!dfa.isPrecedenceDfa() && dfa.atnStartState instanceof StarLoopEntryState) {
		if (((StarLoopEntryState)dfa.atnStartState).precedenceRuleDecision) {
			dfa.setPrecedenceDfa(true);
		}
	}

This clearly changes an existing DFA from being a non precedence one to being a precedence one, which leads to change the allocation strategy.


In a multi threaded context, you can therefore simultaneously have 1 thread executing the below in addDFAEdge:

	if ( from.edges==null ) {
		from.edges = new DFAState[atn.maxTokenType+1+1];
	}
		
	from.edges[t+1] = to; // connect

and another thread executing the below in dfa.setPrecedenceStartState:

s0.edges = Arrays.copyOf(s0.edges, precedence + 1);

if the latter occurs between the former allocation and assignment, we could observe the behaviour.

This could happen as a consequence of: dfa.s0 = s0; in adaptivePredict, which is done after checking for the precedence nature of the DFA, but might have been changed in between by another thread.

In brief, I would delegate s0 assignment to DFA so it can be reliably protected and see if it improves.
I would also delegate edges allocation to DFA.

**Comment by parrt** [comment]
Great job, guys! Thanks. sounds suspicious as you say.

**Comment by sharwell** [comment]
This is one of the more... "interesting" portions of the algorithm for sure. The above situation can only be a problem if `from` variable in the first section and `s0` variable of the second section refer to the same instance. By design, the `DFAState` created for a precedence DFA is not added to the `DFA.states` collection, which means the only way to reach this *particular* `DFAState` instance is by accessing the `DFA.s0` field directly. The code path in `adaptivePredict` which uses the `DFA.s0` field for a precedence DFA always immediately follows an outgoing edge according to the current precedence level in the parser, so there is no way for that instance to end up in `addDFAEdge` as the `from` state.

**Comment by sharwell** [comment]
Note that while `adaptivePredict` can call `dfa.setPrecedenceDfa(true)`, there is no case where an existing `DFA` instance will transition from being a precedence DFA back to a normal DFA. This is a vital condition for the code flow around the block in `adaptivePredict` which assigns `dfa.s0 = s0`.

**Comment by ericvergnaud** [comment]
An I correct in observing that adaptivePredict is only called during testing/profiling?
If so, this may be an almost non problem i.e. we could prevent concurrent execution of adaptivePredict without impacting performance.

**Comment by sharwell** [comment]
No, `adaptivePredict` is the entry point to the prediction algorithm and the primary focus point of almost every performance-related issue in ANTLR 4.

**Comment by sharwell** [comment]
`adaptivePredict` has two key "modes" of operation. The "warmup" path is when DFA states are getting calculated and edges are being added to the dynamically-generated DFA. The "fast" path is when future input follows edges of the DFA which were previously computed and cached. During triage for a large customer working with ANTLR, it became clear that it's *extremely* important that no use of `synchronized` appear anywhere on the "fast" path.

Unlike some systems where "warmup" is strictly before the "fast" path, ANTLR 4 is generally observed to continue adding DFA states as new input is received throughout the parsing process. However, the bulk of this occurs during the "first few files", after which point the majority of decisions end up going through the DFA.

**Comment by ericvergnaud** [comment]
Yeah it’s all over the place in generated code, but my IDE of course only sees it in non generated code.
It would still be useful to temporarily mark it as synchronized and see if the problem disappears.
This would increase our confidence on where the issue lies.

**Comment by martint** [comment]
FWIW, we're seeing this issue intermittently in our system, too:

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.antlr.v4.runtime.atn.ParserATNSimulator.addDFAEdge(ParserATNSimulator.java:1838)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.computeTargetState(ParserATNSimulator.java:609)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:483)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:423)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:1319)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:1173)
	at com.facebook.presto.sql.parser.SqlBaseParser.query(SqlBaseParser.java:1039)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:743)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:147)
	at com.facebook.presto.sql.parser.SqlParser$$Lambda$3/926727210.apply(Unknown Source)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:93)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:66)
    ...
```

**Comment by parrt** [comment]
Hi Martin. wow, it's a party! Anything you can do to provide a (smallest possible) test that intermittently causes this issue would be much appreciated and would facilitate a quick fix. This bug concerns me greatly. Sam and Eric have already thought about this quite a bit I will jump into it as soon as I catch up after this first week of school, hopefully.

**Comment by sharwell** [comment]
Thanks @martint. The specific index included in the exception message made me realize what the problem is. The failure sequence is:

1. Thread 1 [checks `dfa.isPrecedenceDfa()`](https://github.com/antlr/antlr4/blob/8d9c7d280151916826db9f953d6b49e0c4eb1f00/runtime/Java/src/org/antlr/v4/runtime/atn/ParserATNSimulator.java#L372)
2. Thread 2 [calls `dfa.setPrecedenceDfa(true)`](https://github.com/antlr/antlr4/blob/8d9c7d280151916826db9f953d6b49e0c4eb1f00/runtime/Java/src/org/antlr/v4/runtime/atn/ParserATNSimulator.java#L397)
3. Thread 1 [reads `s0` as the start state](https://github.com/antlr/antlr4/blob/8d9c7d280151916826db9f953d6b49e0c4eb1f00/runtime/Java/src/org/antlr/v4/runtime/atn/ParserATNSimulator.java#L379), but it should have instead [followed a precedence edge to find the start state](https://github.com/antlr/antlr4/blob/8d9c7d280151916826db9f953d6b49e0c4eb1f00/runtime/Java/src/org/antlr/v4/runtime/atn/ParserATNSimulator.java#L375)

I'll send a fix later today.

**Comment by parrt** [comment]
Hooray! Crowd-sourcing at it's finest! :)

**Comment by electrum** [comment]
Thanks for fixing this! Any chance of getting a new release with this fix? Or if that's a big deal, getting a point release with just this fix? We hit this error quite frequently.

**Comment by parrt** [comment]
well it’s kind of a major transaction cost to get out a new release.  how about if I provide a jar? ;)
Ter
